// =============================================
// FIELD OF PLAY - Müsabaka Alanı
// =============================================

window.DAY2_SECTIONS = [
  { id: "d2_ekipman",  label: "Ekipman Kontrolü" },
  { id: "d2_kose",     label: "Köşe Görevlisi" },
  { id: "d2_juri_rap", label: "Jüri: Raporlama" },
  { id: "d2_juri_diy", label: "Jüri: Genel İletişim" },
  { id: "d2_juri_gov", label: "Jüri: Görevlendirme" },
  { id: "d2_yan",      label: "Yan Hakem" },
  { id: "d2_skor",     label: "Skor Sistemi" },
  { id: "d2_zaman",    label: "Zaman Hakemi" },
  { id: "d2_anons",    label: "Anons Hakemi" },
  { id: "d2_orta",     label: "Orta Hakem" },
  { id: "d2_uyari",    label: "Uyarılar" },
  { id: "d2_faul",     label: "Fauller" },
  { id: "d2_ceza",     label: "Cezalar" },
  { id: "d2_karar",    label: "Kararlar" },
  { id: "d2_saglik",   label: "Sporcu Sağlığı" },
  { id: "d2_doktor",   label: "Doktor" },
  { id: "d2_ring",     label: "Ring" },
  { id: "d2_hakem",    label: "Hakem Sağlığı" },
  { id: "d2_senaryo",  label: "▶ Senaryo Pratiği" },
];

window.DAY2_PHRASES = {
  d2_ekipman: [
    { en: "Only IFMA approved gloves are allowed.", alt: "IFMA gloves only.", ph: "Onli IFMA ıpruuvd glavz ar ılaud.", phs: "IFMA glavz onli.", tr: "Sadece IFMA onaylı eldivenlere izin verilir." },
    { en: "These gloves are not acceptable. Please change them.", alt: "Not acceptable. Change, please.", ph: "Diiz glavz ar not akseptıbıl. Pliiz çeync dem.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu eldivenler uygun değil. Lütfen değiştirin." },
    { en: "These shin guards are not acceptable. Please change them.", alt: "Not acceptable. Change, please.", ph: "Diiz şin gardz ar not akseptıbıl. Pliiz çeync dem.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu kaval koruyucular uygun değil. Lütfen değiştirin." },
    { en: "This gum shield is not acceptable. Please change it.", alt: "Not acceptable. Change, please.", ph: "Dis gam şiild iz not akseptıbıl. Pliiz çeync it.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu dişlik uygun değil. Lütfen değiştirin." },
    { en: "This chest protector is not acceptable. Please change it.", alt: "Not acceptable. Change, please.", ph: "Dis çest prıtektır iz not akseptıbıl. Pliiz çeync it.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu göğüs koruyucu uygun değil. Lütfen değiştirin." },
    { en: "This headguard is not acceptable. Please change it.", alt: "Not acceptable. Change, please.", ph: "Dis hedgard iz not akseptıbıl. Pliiz çeync it.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu kask uygun değil. Lütfen değiştirin." },
    { en: "These shorts are not approved. Please change them.", alt: "Not approved. Change, please.", ph: "Diiz şorts ar not ıpruuvd. Pliiz çeync dem.", phs: "Not ıpruuvd. Çeync pliiz.", tr: "Bu şort onaylı değil. Lütfen değiştirin." },
    { en: "This shirt is not approved. Please change it.", alt: "Not approved. Change, please.", ph: "Dis şört iz not ıpruuvd. Pliiz çeync it.", phs: "Not ıpruuvd. Çeync pliiz.", tr: "Bu tişört onaylı değil. Lütfen değiştirin." },
    { en: "This bandage is not acceptable. Please change it.", alt: "Not acceptable. Change, please.", ph: "Dis bandıc iz not akseptıbıl. Pliiz çeync it.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu bandaj uygun değil. Lütfen değiştirin." },
    { en: "Please remove your jewelry. It is not allowed.", alt: "Jewelry off.", ph: "Pliiz rimuuv yor cuulri. İt iz not ılaud.", phs: "Cuulri of.", tr: "Lütfen takılarınızı çıkarın. Yasaktır." },
    { en: "The gloves are loose. Please tape them.", alt: "Tape the gloves.", ph: "Dı glavz ar luus. Pliiz teyp dem.", phs: "Teyp dı glavz.", tr: "Eldivenler gevşek. Lütfen bantlayın." },
    { en: "The shin guards are loose. Please tape them.", alt: "Tape the shin guards.", ph: "Dı şin gardz ar luus. Pliiz teyp dem.", phs: "Teyp dı şin gardz.", tr: "Kaval koruyucular gevşek. Lütfen bantlayın." },
    { en: "Please tuck your shirt into your shorts.", alt: "Tuck in your shirt.", ph: "Pliiz tak yor şört intu yor şorts.", phs: "Tak in yor şört.", tr: "Lütfen tişörtünüzü şortunuzun içine sokun." },
    { en: "Please use a hair net.", alt: "Hair net, please.", ph: "Pliiz yuuz ey her net.", phs: "Her net pliiz.", tr: "Lütfen saç filesi kullanın." },
    { en: "Put in your gum shield.", alt: "Gum shield in.", ph: "Put in yor gam şiild.", phs: "Gam şiild in.", tr: "Dişliğini tak." },
    { en: "Put on your headguard.", alt: "Headguard on.", ph: "Put on yor hedgard.", phs: "Hedgard on.", tr: "Kaskını tak." },
    { en: "Remove your headguard.", alt: "Headguard off.", ph: "Rimuuv yor hedgard.", phs: "Hedgard of.", tr: "Kaskını çıkar." },
    { en: "Put on your Mongkon.", alt: "Mongkon on.", ph: "Put on yor Mongkon.", phs: "Mongkon on.", tr: "Mongkon'unu tak." },
    { en: "Remove your Mongkon.", alt: "Mongkon off.", ph: "Rimuuv yor Mongkon.", phs: "Mongkon of.", tr: "Mongkon'unu çıkar." },
    { en: "Show me your bandage.", alt: "Bandage?", ph: "Şoo mi yor bandıc.", phs: "Bandıc?", tr: "Bandajını göster." },
    { en: "The gloves must be 10 oz.", alt: "10 oz gloves only.", ph: "Dı glavz mast bi ten auns.", phs: "Ten auns glavz onli.", tr: "Eldivenler 10 ons olmalı." },
    { en: "Can I see your gloves?", alt: "Gloves?", ph: "Kan ay sii yor glavz?", phs: "Glavz?", tr: "Eldivenlerini görebilir miyim?" },
    { en: "Can I see your headguard?", alt: "Headguard?", ph: "Kan ay sii yor hedgard?", phs: "Hedgard?", tr: "Kaskını görebilir miyim?" },
    { en: "Can I see your gum shield?", alt: "Gum shield?", ph: "Kan ay sii yor gam şiild?", phs: "Gam şiild?", tr: "Dişliğini görebilir miyim?" },
    { en: "Do you have a groin guard?", alt: "Groin guard?", ph: "Duu yu hav ey groyn gard?", phs: "Groyn gard?", tr: "Kasık koruyucunuz var mı?" },
    { en: "Do you have a chest protector?", alt: "Chest protector?", ph: "Duu yu hav ey çest prıtektır?", phs: "Çest prıtektır?", tr: "Göğüs koruyucunuz var mı?" },
    { en: "Ankle protection is not allowed.", alt: "No ankle protection.", ph: "Ankıl prıtekşın iz not ılaud.", phs: "Noo ankıl prıtekşın.", tr: "Ayak bilek koruyucusuna izin verilmez." },
    { en: "The hijab/body suit must be white.", alt: "White hijab/body suit only.", ph: "Dı hicab / badi suut mast bi vayt.", phs: "Vayt hicab / badi suut onli.", tr: "Hicap / Body suit beyaz olmalıdır." },
    { en: "Your toenails are too long. Please trim them.", alt: "Trim your toenails.", ph: "Yor tooneylz ar tuu long. Pliiz trim dem.", phs: "Trim yor tooneylz.", tr: "Ayak tırnaklarınız çok uzun. Lütfen kesin." },
    { en: "Too much Vaseline. Please wipe it off.", alt: "Wipe the Vaseline.", ph: "Tuu maç vazıliin. Pliiz vayp it of.", phs: "Vayp dı vazıliin.", tr: "Çok fazla Vazelin var. Lütfen silin." },
  ],

  d2_kose: [
    { en: "Only sports shoes are allowed.", alt: "Sports shoes only.", ph: "Onli sports şuuz ar ılaud.", phs: "Sports şuuz onli.", tr: "Sadece spor ayakkabıya izin verilir." },
    { en: "Please remove your jacket.", alt: "Jacket off.", ph: "Pliiz rimuuv yor cakıt.", phs: "Cakıt of.", tr: "Lütfen ceketinizi çıkarın." },
    { en: "You may put on the headguard.", alt: "Headguard on.", ph: "Yu mey put on dı hedgard.", phs: "Hedgard on.", tr: "Kaskı takabilirsiniz." },
    { en: "You may remove the headguard.", alt: "Headguard off.", ph: "Yu mey rimuuv dı hedgard.", phs: "Hedgard of.", tr: "Kaskı çıkarabilirsiniz." },
    { en: "Do not remove the gloves.", alt: "Gloves stay on.", ph: "Duu not rimuuv dı glavz.", phs: "Glavz stey on.", tr: "Eldivenleri çıkarmayın." },
    { en: "Good luck.", alt: "Good luck.", ph: "Gud lak.", phs: "Gud lak.", tr: "Başarılar dilerim." },
    { en: "Please take the water bottle.", alt: "Water bottle.", ph: "Pliiz teyk dı votır botıl.", phs: "Votır botıl.", tr: "Lütfen su şişesini alın." },
    { en: "Do not use too much water.", alt: "Less water.", ph: "Duu not yuuz tuu maç votır.", phs: "Les votır.", tr: "Çok fazla su kullanmayın." },
    { en: "Fix the elbow guard.", alt: "Fix the elbow guard.", ph: "Fiks dı elboo gard.", phs: "Fiks dı elboo gard.", tr: "Dirsekliği düzeltin." },
    { en: "Fix the headguard.", alt: "Fix the headguard.", ph: "Fiks dı hedgard.", phs: "Fiks dı hedgard.", tr: "Kaskı düzeltin." },
    { en: "Fix the gloves.", alt: "Fix the gloves.", ph: "Fiks dı glavz.", phs: "Fiks dı glavz.", tr: "Eldivenleri düzeltin." },
    { en: "Fix the chest protector.", alt: "Fix the chest protector.", ph: "Fiks dı çest prıtektır.", phs: "Fiks dı çest prıtektır.", tr: "Göğüs koruyucuyu düzeltin." },
    { en: "Tape the elbow guard.", alt: "Tape the elbow guard.", ph: "Teyp dı elboo gard.", phs: "Teyp dı elboo gard.", tr: "Dirsekliği bantlayın." },
    { en: "Please remove the Prajiad.", alt: "Prajiad off.", ph: "Pliiz rimuuv dı Praciad.", phs: "Praciad of.", tr: "Lütfen Prajiad'ı çıkarın." },
    { en: "Tape the gloves.", alt: "Tape the gloves.", ph: "Teyp dı glavz.", phs: "Teyp dı glavz.", tr: "Eldivenleri bantlayın." },
    { en: "Tape the shin guards.", alt: "Tape the shin guards.", ph: "Teyp dı şin gardz.", phs: "Teyp dı şin gardz.", tr: "Kaval koruyucuları bantlayın." },
    { en: "Please remove the towel.", alt: "Towel away.", ph: "Pliiz rimuuv dı tauıl.", phs: "Tauıl evey.", tr: "Lütfen havluyu kaldırın." },
    { en: "Please lean over the ropes.", alt: "Over the ropes.", ph: "Pliiz liin ovır dı roops.", phs: "Ovır dı roops.", tr: "Lütfen iplerden dışarı eğilin." },
    { en: "The gum shield colour is not correct. It must be red or pink. Please change it.", alt: "Wrong colour. Change it.", ph: "Dı gam şiild kalır iz not korekt. İt mast bi red or pink. Pliiz çeync it.", phs: "Rong kalır. Çeync it.", tr: "Dişlik rengi doğru değil. Kırmızı veya pembe olmalı. Lütfen değiştirin." },
  ],

  d2_juri_rap: [
    { en: "I counted once in the same round.", alt: "One count, same round.", ph: "Ay kauntıd vans in dı seym raund.", phs: "Van kaunt, seym raund.", tr: "Aynı raundda 1 kere saydım." },
    { en: "I counted twice in the same round.", alt: "Two counts, same round.", ph: "Ay kauntıd tways in dı seym raund.", phs: "Tuu kaunts, seym raund.", tr: "Aynı raundda 2 kere saydım." },
    { en: "I counted three times in the same round.", alt: "Three counts, same round.", ph: "Ay kauntıd thrii taymz in dı seym raund.", phs: "Thrii kaunts, seym raund.", tr: "Aynı raundda 3 kere saydım." },
    { en: "I counted twice in total.", alt: "Two counts total.", ph: "Ay kauntıd tways in tootıl.", phs: "Tuu kaunts tootıl.", tr: "Toplamda 2 kere saydım." },
    { en: "I counted three times in total.", alt: "Three counts total.", ph: "Ay kauntıd thrii taymz in tootıl.", phs: "Thrii kaunts tootıl.", tr: "Toplamda 3 kere saydım." },
    { en: "I gave two cautions.", alt: "Two cautions.", ph: "Ay geyv tuu kooşınz.", phs: "Tuu kooşınz.", tr: "2 kere uyarı verdim." },
    { en: "I gave three cautions.", alt: "Three cautions.", ph: "Ay geyv thrii kooşınz.", phs: "Thrii kooşınz.", tr: "3 kere uyarı verdim." },
    { en: "The athlete has no bandage.", alt: "No bandage.", ph: "Dı etliit haz noo bandıc.", phs: "Noo bandıc.", tr: "Sporcunun bandajı yok." },
    { en: "Can they change the headguard?", alt: "Change headguard?", ph: "Kan dey çeync dı hedgard?", phs: "Çeync hedgard?", tr: "Kaskı değiştirebilirler mi?" },
    { en: "Can you give me a hair net?", alt: "Hair net, please.", ph: "Kan yu giv mi ey her net?", phs: "Her net, pliiz.", tr: "Saç filesi verir misiniz?" },
    { en: "Can you give me some tape?", alt: "Tape, please.", ph: "Kan yu giv mi sam teyp?", phs: "Teyp, pliiz.", tr: "Bant verebilir misiniz?" },
    { en: "The athlete's toenails are too long.", alt: "Toenails too long.", ph: "Dı etliits tooneylz ar tuu long.", phs: "Tooneylz tuu long.", tr: "Sporcunun ayak tırnakları uzun." },
    { en: "The athlete's hijab is not approved.", alt: "Hijab not approved.", ph: "Dı etliits hicab iz not ıpruuvd.", phs: "Hicab not ıpruuvd.", tr: "Sporcunun baş örtüsü uygun değil." },
    { en: "The athlete has no groin guard.", alt: "No groin guard.", ph: "Dı etliit haz noo groyn gard.", phs: "Noo groyn gard.", tr: "Sporcunun kasık koruyucusu yok." },
    { en: "The athlete has no chest protector.", alt: "No chest protector.", ph: "Dı etliit haz noo çest prıtektır.", phs: "Noo çest prıtektır.", tr: "Sporcunun göğüs koruyucusu yok." },
    { en: "The headguard is not approved. It must be changed.", alt: "Headguard not approved. Must be changed.", ph: "Dı hedgard iz not ıpruuvd. İt mast bi çeyncd.", phs: "Hedgard not ıpruuvd. Mast bi çeyncd.", tr: "Kask uygun değil, değiştirilmeli." },
    { en: "The gloves are not approved. They must be changed.", alt: "Gloves not approved. Must be changed.", ph: "Dı glavz ar not ıpruuvd. Dey mast bi çeyncd.", phs: "Glavz not ıpruuvd. Mast bi çeyncd.", tr: "Eldiven uygun değil, değiştirilmeli." },
    { en: "The elbow guard is not approved. It must be changed.", alt: "Elbow guard not approved. Must be changed.", ph: "Dı elboo gard iz not ıpruuvd. İt mast bi çeyncd.", phs: "Elboo gard not ıpruuvd. Mast bi çeyncd.", tr: "Dirseklik uygun değil, değiştirilmeli." },
    { en: "The chest protector is not approved. It must be changed.", alt: "Chest protector not approved. Must be changed.", ph: "Dı çest prıtektır iz not ıpruuvd. İt mast bi çeyncd.", phs: "Çest prıtektır not ıpruuvd. Mast bi çeyncd.", tr: "Göğüs koruyucu uygun değil, değiştirilmeli." },
  ],

  d2_juri_diy: [
    { en: "I need to make a phone call. May I?", alt: "Phone call. May I?", ph: "Ay niid tu meyk ey foon kool. Mey ay?", phs: "Foon kool. Mey ay?", tr: "Telefon görüşmesi yapmam gerekiyor. Gidebilir miyim?" },
    { en: "May I go to the restroom?", alt: "Restroom. May I?", ph: "Mey ay goo tu dı restruum?", phs: "Restruum. Mey ay?", tr: "Lavaboya gidebilir miyim?" },
    { en: "Thank you for your understanding.", alt: "Thank you.", ph: "Thenk yu for yor andırstendıng.", phs: "Thenk yu.", tr: "Anlayışınız için teşekkür ederim." },
    { en: "Thank you for your feedback. I will be careful.", alt: "Thank you. I'll be careful.", ph: "Thenk yu for yor fiidbek. Ay vil bi kerful.", phs: "Thenk yu. Ayl bi kerful.", tr: "Geri bildiriminiz için teşekkür ederim. Dikkat edeceğim." },
    { en: "I am sorry for my mistake. I will be careful.", alt: "Sorry. I'll be careful.", ph: "Ay em sori for may misteyk. Ay vil bi kerful.", phs: "Sori. Ayl bi kerful.", tr: "Hatam için özür dilerim. Dikkat edeceğim." },
    { en: "I can help you.", alt: "I can help.", ph: "Ay kan help yu.", phs: "Ay kan help.", tr: "Yardım edebilirim." },
    { en: "Can you help me, please?", alt: "Help me, please.", ph: "Kan yu help mi, pliiz?", phs: "Help mi, pliiz.", tr: "Bana yardımcı olabilir misiniz?" },
  ],

  d2_juri_gov: [
    { en: "Do I have a duty?", alt: "Any duty for me?", ph: "Duu ay hav ey dyuuti?", phs: "Eni dyuuti for mi?", tr: "Görevim var mı?" },
    { en: "What is my duty?", alt: "My duty?", ph: "Vat iz may dyuuti?", phs: "May dyuuti?", tr: "Görevim nedir?" },
    { en: "Which number should I go to?", alt: "Which number?", ph: "Viç nambır şud ay goo tu?", phs: "Viç nambır?", tr: "Kaç numaraya geçeceğim?" },
    { en: "Which weight division is it?", alt: "Which division?", ph: "Viç veyt divıcın iz it?", phs: "Viç divıcın?", tr: "Hangi sıklet?" },
    { en: "Which category is it?", alt: "Which category?", ph: "Viç ketıgori iz it?", phs: "Viç ketıgori?", tr: "Hangi kategori?" },
    { en: "May I check the duty list?", alt: "Duty list, please?", ph: "Mey ay çek dı dyuuti list?", phs: "Dyuuti list, pliiz?", tr: "Görev listesine bakabilir miyim?" },
    { en: "Which bout number is it?", alt: "Which bout?", ph: "Viç baut nambır iz it?", phs: "Viç baut?", tr: "Kaçıncı maç?" },
    { en: "Which ring is it?", alt: "Which ring?", ph: "Viç ring iz it?", phs: "Viç ring?", tr: "Hangi ring?" },
  ],

  d2_yan: [
    { en: "The scorecard is finished.", alt: "No scorecards left.", ph: "Dı skoorkard iz finişt.", phs: "Noo skoorkard left.", tr: "Skor kartı bitti." },
    { en: "I need a pen, please.", alt: "Pen, please.", ph: "Ay niid ey pen, pliiz.", phs: "Pen, pliiz.", tr: "Kaleme ihtiyacım var." },
    { en: "Please step back.", alt: "Step back.", ph: "Pliiz step bek.", phs: "Step bek.", tr: "Lütfen geriye gidiniz." },
  ],

  d2_skor: [
    { en: "I am pressing the button.", alt: "I'm pressing.", ph: "Ay em presıng dı batın.", phs: "Aym presıng.", tr: "Butona basıyorum." },
    { en: "I did not press the button.", alt: "Didn't press.", ph: "Ay did not pres dı batın.", phs: "Didnt pres.", tr: "Butona basmadım." },
    { en: "I pressed the wrong button.", alt: "Wrong button.", ph: "Ay prest dı rong batın.", phs: "Rong batın.", tr: "Butona yanlış bastım." },
    { en: "I reset the score by mistake.", alt: "Reset by mistake.", ph: "Ay riiset dı skoor bay misteyk.", phs: "Riiset bay misteyk.", tr: "Yanlışlıkla skoru resetledim." },
    { en: "The cable came out.", alt: "Cable unplugged.", ph: "Dı keybıl keym aut.", phs: "Keybıl anplagd.", tr: "Kablo çıktı." },
    { en: "I gave the point to the wrong corner.", alt: "Wrong corner point.", ph: "Ay geyv dı poynt tu dı rong kornır.", phs: "Rong kornır poynt.", tr: "Yanlış köşeye puan verdim." },
    { en: "Everything is okay.", alt: "All good.", ph: "Evriting iz okey.", phs: "Ol gud.", tr: "Her şey yolunda." },
  ],

  d2_zaman: [
    { en: "The system has stopped.", alt: "System stopped.", ph: "Dı sistım haz stopt.", phs: "Sistım stopt.", tr: "Sistem durdu." },
    { en: "There is no sound.", alt: "No sound.", ph: "Der iz noo saund.", phs: "Noo saund.", tr: "Ses gelmiyor." },
    { en: "I stopped the time.", alt: "Time stopped.", ph: "Ay stopt dı taym.", phs: "Taym stopt.", tr: "Zamanı durdurdum." },
    { en: "I started the time.", alt: "Time started.", ph: "Ay staartıd dı taym.", phs: "Taym staartıd.", tr: "Zamanı başlattım." },
  ],

  d2_anons: [
    { en: "Next bout, red corner [Name] from [Country], blue corner [Name] from [Country], please get ready.", alt: "Next bout, get ready.", ph: "Nekst baut, red kornır [Neym] fram [Kantri], bluu kornır [Neym] fram [Kantri], pliiz get redi.", phs: "Nekst baut, get redi.", tr: "Bir sonraki maçın sporcuları; kırmızı köşe, mavi köşe hazırlansınlar lütfen." },
    { en: "Ring A, Bout number 2, red corner [Name] from [Country] to the ring area!", alt: "Ring A, Bout 2, Red corner to the ring!", ph: "Ring Ey, Baut nambır tuu, red kornır [Neym] fram [Kantri] tu dı ring erya!", phs: "Ring Ey, Baut tuu, Red kornır tu dı ring!", tr: "A Ringi 2. Maç, Kırmızı köşe sporcusu ring alanına!" },
    { en: "Ring B, Bout number 3, blue corner [Name] from [Country] to the ring area!", alt: "Ring B, Bout 3, Blue corner to the ring!", ph: "Ring Bii, Baut nambır thrii, bluu kornır [Neym] fram [Kantri] tu dı ring erya!", phs: "Ring Bii, Baut thrii, Bluu kornır tu dı ring!", tr: "B Ringi 3. Maç, Mavi köşe sporcusu ring alanına!" },
    { en: "This is the final call!", alt: "Final call!", ph: "Dis iz dı faynıl kool!", phs: "Faynıl kool!", tr: "Son çağrı!" },
    { en: "The winner is the red corner.", alt: "Winner, red corner.", ph: "Dı vinır iz dı red kornır.", phs: "Vinır, red kornır.", tr: "Kazanan kırmızı köşe." },
    { en: "The winner is the blue corner.", alt: "Winner, blue corner.", ph: "Dı vinır iz dı bluu kornır.", phs: "Vinır, bluu kornır.", tr: "Kazanan mavi köşe." },
    { en: "The bouts are paused for one hour.", alt: "One hour break.", ph: "Dı bauts ar paazd for van auır.", phs: "Van auır breyk.", tr: "Maçlara bir saat ara verilmiştir." },
    { en: "Seconds out!", alt: "Seconds out!", ph: "Sekındz aut!", phs: "Sekındz aut!", tr: "Yardımcılar dışarı!" },
  ],

  d2_orta: [
    { en: "Red, Blue, come to the center. Shake hands. Good luck.", alt: "Center. Shake hands. Good luck.", ph: "Red, Bluu, kam tu dı sentır. Şeyk hendz. Gud lak.", phs: "Sentır. Şeyk hendz. Gud lak.", tr: "Kırmızı, Mavi ortaya gelin. El sıkışın. Başarılar." },
    { en: "Put on your headguard. Listen to my commands.", alt: "Headguard on. Listen to me.", ph: "Put on yor hedgard. Lisın tu may kımandz.", phs: "Hedgard on. Lisın tu mi.", tr: "Kaskınızı takın. Komutlarımı dinleyin." },
  ],

  d2_uyari: [
    { en: "This is your first caution.", alt: "First caution.", ph: "Dis iz yor ferst kooşın.", phs: "Ferst kooşın.", tr: "Bu sana ilk uyarım." },
    { en: "This is your second caution.", alt: "Second caution.", ph: "Dis iz yor sekınd kooşın.", phs: "Sekınd kooşın.", tr: "Bu sana ikinci uyarım." },
    { en: "This is your last caution.", alt: "Last caution.", ph: "Dis iz yor lest kooşın.", phs: "Lest kooşın.", tr: "Bu sana son uyarım." },
  ],

  d2_faul: [
    { en: "No shaking hands during the fight.", alt: "No shaking hands.", ph: "Noo şeyking hendz dyuuring dı fayt.", phs: "Noo şeyking hendz.", tr: "El sıkışma yok (raund içinde)." },
    { en: "Do not talk during the fight.", alt: "Don't talk.", ph: "Duu not took dyuuring dı fayt.", phs: "Doont took.", tr: "Konuşma." },
    { en: "Do not spit out your gum shield.", alt: "Don't spit the gum shield.", ph: "Duu not spit aut yor gam şiild.", phs: "Doont spit dı gam şiild.", tr: "Dişliğini çıkarma/tükürme." },
    { en: "Tripping or sweeping without Muaythai skill is not allowed.", alt: "No sweep.", ph: "Triping or sviiping vidaut Muaytay skil iz not ılaud.", phs: "Noo sviip.", tr: "Muaythai tekniği olmadan süpürmek yasaktır." },
    { en: "Holding the neck and arm is not allowed.", alt: "No head-arm hold.", ph: "Holding dı nek end arm iz not ılaud.", phs: "Noo hed-arm hoold.", tr: "Kafa-kol yapmak yasaktır." },
    { en: "Headbutting is not allowed.", alt: "No headbutt.", ph: "Hedbating iz not ılaud.", phs: "Noo hedbat.", tr: "Kafa atmak yasaktır." },
    { en: "Pressing on the opponent's eyes with the thumb is not allowed.", alt: "No eye pressing.", ph: "Presıng on dı ıpoonınts ayz vid dı thamb iz not ılaud.", phs: "Noo ay presıng.", tr: "Baş parmakla göze baskı uygulamak yasaktır." },
    { en: "Intentionally removing or displacing equipment is not allowed.", alt: "Don't remove equipment.", ph: "İntenşınıli rimuuvıng or displeysıng ikvipmınt iz not ılaud.", phs: "Doont rimuuv ikvipmınt.", tr: "Ekipmanları kasıtlı çıkarmak/gevşetmek yasaktır." },
    { en: "Throwing an opponent using the hip is not allowed.", alt: "No hip throw.", ph: "Throoing en ıpoonınt yuuzıng dı hip iz not ılaud.", phs: "Noo hip throo.", tr: "Kalçadan fırlatmak yasaktır." },
    { en: "Tackling the opponent's body or legs is not allowed.", alt: "No tackling.", ph: "Teklıng dı ıpoonınts badi or legz iz not ılaud.", phs: "Noo tekling.", tr: "Güreş taktiğiyle dalmak yasaktır." },
    { en: "Immobilizing the opponent's legs is not allowed.", alt: "No leg lock.", ph: "İmoobılayzıng dı ıpoonınts legz iz not ılaud.", phs: "Noo leg lok.", tr: "Rakip bacağını kilitlemek yasaktır." },
    { en: "Lifting an opponent by the body is not allowed.", alt: "No lifting.", ph: "Liftıng en ıpoonınt bay dı badi iz not ılaud.", phs: "Noo lifting.", tr: "Havaya kaldırmak yasaktır." },
    { en: "Striking while holding the ropes is not allowed.", alt: "Don't hold ropes.", ph: "Strayking vayl holding dı roops iz not ılaud.", phs: "Doont hoold roops.", tr: "İpleri tutarak vurmak yasaktır." },
    { en: "Do not use the ropes unfairly.", alt: "Don't use ropes.", ph: "Duu not yuuz dı roops anferli.", phs: "Doont yuuz roops.", tr: "İplerden haksız destek alma." },
    { en: "Falling on to an opponent on the floor is not allowed.", alt: "Don't fall on him.", ph: "Foolıng on tu en ıpoonınt on dı floor iz not ılaud.", phs: "Doont fool on him.", tr: "Düşen sporcunun üstüne bilerek düşmek yasaktır." },
    { en: "Striking a down opponent is not allowed.", alt: "Don't strike a down athlete.", ph: "Strayking ey daun ıpoonınt iz not ılaud.", phs: "Doont strayk ey daun etliit.", tr: "Yerdeki/düşmekte olan sporcuya vurmak yasaktır." },
    { en: "Striking while your body touches the floor is not allowed.", alt: "Don't strike from the floor.", ph: "Strayking vayl yor badi taçız dı floor iz not ılaud.", phs: "Doont strayk fram dı floor.", tr: "Ayak dışında bir yerin yerdeyken vuruş yapmak yasaktır." },
    { en: "Intentionally falling to avoid a hit is not allowed. Fight!", alt: "Don't fall. Fight!", ph: "İntenşınıli foolıng tu ıvoyd ey hit iz not ılaud. Fayt!", phs: "Doont fool. Fayt!", tr: "Darbeden kaçmak için kendini yere atma yasaktır. Dövüş!" },
    { en: "Striking the groin or cervical spine is not allowed.", alt: "No groin, no back of the neck.", ph: "Strayking dı groyn or servıkıl spayn iz not ılaud.", phs: "Noo groyn, noo bek of dı nek.", tr: "Kasığa ve ense bölgesine vuruş yasaktır." },
    { en: "Do not hold the leg.", alt: "Don't hold the leg.", ph: "Duu not hoold dı leg.", phs: "Doont hoold dı leg.", tr: "Bacak tutmak yasaktır." },
    { en: "Do not hold the arm.", alt: "Don't hold the arm.", ph: "Duu not hoold dı arm.", phs: "Doont hoold dı arm.", tr: "Kol tutmak yasaktır." },
    { en: "Do not hold the gloves.", alt: "Don't hold the gloves.", ph: "Duu not hoold dı glavz.", phs: "Doont hoold dı glavz.", tr: "Eldiven tutmak yasaktır." },
    { en: "Pushing forward more than two steps without striking is not allowed.", alt: "Two steps only. Strike!", ph: "Puşing forvırd moor den tuu steps vidaut strayking iz not ılaud.", phs: "Tuu steps onli. Strayk!", tr: "Vurmadan 2 adımdan fazla ilerleme yasaktır." },
    { en: "Striking after the round has ended is not allowed. Listen to me!", alt: "No strike after YOOT.", ph: "Strayking aftır dı raund haz endıd iz not ılaud. Lisın tu mi!", phs: "Noo strayk aftır YUUT.", tr: "Yoot komutundan sonra vuruş yapmak yasaktır!" },
    { en: "You must follow the YOOT or YAEK command immediately.", alt: "Obey YOOT and YAEK.", ph: "Yu mast foloo dı YUUT or YEK kımand imiidiyıtli.", phs: "Obey YUUT end YEK.", tr: "Yoot veya Yaek komutuna uymak zorundasın." },
    { en: "Useless or aggressive utterance is not allowed. Calm down.", alt: "Calm down. No talking.", ph: "Yuuslıs or egresiv atırıns iz not ılaud. Kam daun.", phs: "Kam daun. Noo tooking.", tr: "Agresif/gereksiz konuşma yasaktır. Sakin ol." },
    { en: "No knees to the head.", alt: "No knee to head.", ph: "Noo niiz tu dı hed.", phs: "Noo nii tu hed.", tr: "Kafaya diz yasaktır." },
    { en: "No elbows to the head.", alt: "No elbow to head.", ph: "Noo elbooz tu dı hed.", phs: "Noo elboo tu hed.", tr: "Kafaya dirsek yasaktır." },
    { en: "No strikes to the head.", alt: "No strike to head.", ph: "Noo strayks tu dı hed.", phs: "Noo strayk tu hed.", tr: "Kafaya vuruş yasaktır." },
    { en: "No strikes to the face.", alt: "No strike to face.", ph: "Noo strayks tu dı feys.", phs: "Noo strayk tu feys.", tr: "Yüze vuruş yasaktır." },
  ],

  d2_ceza: [
    { en: "Warning for unsportsmanlike behaviour.", alt: "[Colour], Warning, Unsportsmanlike.", ph: "Vorning for ansportsmınlayk biheyvyır.", phs: "[Reng] Vorning, Ansportsmınlayk.", tr: "Sportmenlik dışı davranış — Ceza (Warning)." },
    { en: "Warning for striking a down opponent.", alt: "[Colour], Warning, Striking down athlete.", ph: "Vorning for strayking ey daun ıpoonınt.", phs: "[Reng] Vorning, Strayking daun etliit.", tr: "Yerdeki sporcuya vurma — Ceza (Warning)." },
    { en: "Warning for removing the gum shield.", alt: "[Colour], Warning, Gum shield.", ph: "Vorning for rimuuvıng dı gam şiild.", phs: "[Reng] Vorning, Gam şiild.", tr: "Dişliği bilerek çıkarma — Ceza (Warning)." },
    { en: "Warning for illegal sweep.", alt: "[Colour], Warning, Illegal sweep.", ph: "Vorning for iliigıl sviip.", phs: "[Reng] Vorning, İliigıl sviip.", tr: "Kuralsız süpürme — Ceza (Warning)." },
    { en: "Warning for wrestling.", alt: "[Colour], Warning, Wrestling.", ph: "Vorning for resling.", phs: "[Reng] Vorning, Resling.", tr: "Güreşme/sarılıp dalma — Ceza (Warning)." },
    { en: "Warning for biting.", alt: "[Colour], Warning, Biting.", ph: "Vorning for bayting.", phs: "[Reng] Vorning, Bayting.", tr: "Rakibi ısırma — Ceza (Warning)." },
    { en: "Warning for headbutting.", alt: "[Colour], Warning, Headbutt.", ph: "Vorning for hedbating.", phs: "[Reng] Vorning, Hedbat.", tr: "Rakibe kafa atma — Ceza (Warning)." },
    { en: "Warning for spitting.", alt: "[Colour], Warning, Spitting.", ph: "Vorning for spiting.", phs: "[Reng] Vorning, Spiting.", tr: "Tükürme — Ceza (Warning)." },
    { en: "Warning for knee to the head.", alt: "[Colour], Warning, Knee to head.", ph: "Vorning for nii tu dı hed.", phs: "[Reng] Vorning, Nii tu hed.", tr: "Kafaya diz — Ceza (Warning)." },
    { en: "Warning for elbow to the head.", alt: "[Colour], Warning, Elbow to head.", ph: "Vorning for elboo tu dı hed.", phs: "[Reng] Vorning, Elboo tu hed.", tr: "Kafaya dirsek — Ceza (Warning)." },
    { en: "Warning for strike to the head.", alt: "[Colour], Warning, Strike to head.", ph: "Vorning for strayk tu dı hed.", phs: "[Reng] Vorning, Strayk tu hed.", tr: "Yasak kafaya vuruş — Ceza (Warning)." },
  ],

  d2_karar: [
    { en: "WP — Win on Points", alt: "Winner is Red/Blue.", ph: "Dabıl-yu Pii — Vin on Poynts", phs: "Vinır iz Red / Bluu.", tr: "Puanla Kazanma" },
    { en: "RSC-S — Referee Stops Contest (Safety)", alt: "Winner is Red/Blue.", ph: "Ar Es Sii Es — Referii Stops Kontest (Seyfti)", phs: "Vinır iz Red / Bluu.", tr: "Hakem Kararıyla Durdurma — Güvenlik" },
    { en: "RSC-I — Referee Stops Contest (Injury)", alt: "Winner is Red/Blue.", ph: "Ar Es Sii Ay — Referii Stops Kontest (İncıri)", phs: "Vinır iz Red / Bluu.", tr: "Hakem Kararıyla Durdurma — Sakatlık" },
    { en: "RSC-H — Referee Stops Contest (Head Strike)", alt: "Winner is Red/Blue.", ph: "Ar Es Sii Eyç — Referii Stops Kontest (Hed Strayk)", phs: "Vinır iz Red / Bluu.", tr: "Hakem Kararıyla Durdurma — Kafaya Ağır Darbe" },
    { en: "RSC-B — Referee Stops Contest (Body Strike)", alt: "Winner is Red/Blue.", ph: "Ar Es Sii Bii — Referii Stops Kontest (Badi Strayk)", phs: "Vinır iz Red / Bluu.", tr: "Hakem Kararıyla Durdurma — Gövdeye Ağır Darbe" },
    { en: "CCL — Compulsory Count Limit", alt: "Winner is Red/Blue.", ph: "Sii Sii El — Kampalsıri Kaunt Limıt", phs: "Vinır iz Red / Bluu.", tr: "Zorunlu Sayma Limitinin Dolması" },
    { en: "KO-H — Knockout (Head Strike)", alt: "Winner is Red/Blue.", ph: "Key Oo Eyç — Nokaut (Hed Strayk)", phs: "Vinır iz Red / Bluu.", tr: "Nakavt — Kafaya Darbe" },
    { en: "KO-B — Knockout (Body Strike)", alt: "Winner is Red/Blue.", ph: "Key Oo Bii — Nokaut (Badi Strayk)", phs: "Vinır iz Red / Bluu.", tr: "Nakavt — Gövdeye Darbe" },
    { en: "RET — Retirement", alt: "Winner is Red/Blue.", ph: "Ar İi Tii — Ritayırmınt", phs: "Vinır iz Red / Bluu.", tr: "Çekilme / Köşenin maçı bırakması" },
    { en: "DQ — Disqualification", alt: "Winner is Red/Blue.", ph: "Dii Kyuu — Diskuolıfikeyşın", phs: "Vinır iz Red / Bluu.", tr: "Diskalifiye" },
    { en: "WO — Walk Over", alt: "Winner is Red/Blue.", ph: "Dabıl-yu Oo — Vook Ovır", phs: "Vinır iz Red / Bluu.", tr: "Hükmen Kazanma — Rakip ringe çıkmadı" },
    { en: "DRAW — No winner.", alt: "Draw.", ph: "Droo — Noo Vinır.", phs: "Droo.", tr: "Beraberlik — Kazanan yok" },
  ],

  d2_saglik: [
    { en: "The athlete's nose is bleeding.", alt: "Nose bleeding.", ph: "Dı etliits nooz iz bliiding.", phs: "Nooz bliiding.", tr: "Sporcunun burnu kanıyor." },
    { en: "The athlete took a heavy strike to the head.", alt: "Heavy head strike.", ph: "Dı etliit tuk ey hevi strayk tu dı hed.", phs: "Hevi hed strayk.", tr: "Sporcu başına ağır darbe aldı." },
    { en: "The athlete took a heavy strike to the groin.", alt: "Heavy groin strike.", ph: "Dı etliit tuk ey hevi strayk tu dı groyn.", phs: "Hevi groyn strayk.", tr: "Sporcu kasığına ağır darbe aldı." },
    { en: "The athlete took a heavy strike to the body.", alt: "Heavy body strike.", ph: "Dı etliit tuk ey hevi strayk tu dı badi.", phs: "Hevi badi strayk.", tr: "Sporcu gövdesine ağır darbe aldı." },
    { en: "The athlete vomited.", alt: "Vomited.", ph: "Dı etliit vamitıd.", phs: "Vamitıd.", tr: "Sporcu kustu." },
    { en: "The athlete fainted.", alt: "Fainted.", ph: "Dı etliit feyntıd.", phs: "Feyntıd.", tr: "Sporcu bayıldı." },
    { en: "Are you okay?", alt: "Okay?", ph: "Ar yu okey?", phs: "Okey?", tr: "İyi misin?" },
    { en: "Will you continue?", alt: "Continue?", ph: "Vil yu kantinyu?", phs: "Kantinyu?", tr: "Devam edecek misin?" },
    { en: "Do you not want to continue?", alt: "You don't want to?", ph: "Duu yu not vant tu kantinyu?", phs: "Yu doont vant tu?", tr: "Devam etmek istemiyor musun?" },
  ],

  d2_doktor: [
    { en: "Can the athlete continue?", alt: "Can he continue?", ph: "Kan dı etliit kantinyu?", phs: "Kan hi kantinyu?", tr: "Sporcu devam edebilir mi?" },
    { en: "What is the situation?", alt: "What's the situation?", ph: "Vat iz dı siçueyşın?", phs: "Vats dı siçueyşın?", tr: "Durum nedir?" },
    { en: "Please do not enter the ring.", alt: "Don't enter the ring.", ph: "Pliiz duu not entır dı ring.", phs: "Doont entır dı ring.", tr: "Ringe girmeyin." },
    { en: "You may enter the ring.", alt: "Enter the ring.", ph: "Yu mey entır dı ring.", phs: "Entır dı ring.", tr: "Ringe girebilirsiniz." },
  ],

  d2_ring: [
    { en: "The canvas needs to be fixed.", alt: "Fix the canvas.", ph: "Dı kenvıs niidz tu bi fikst.", phs: "Fiks dı kenvıs.", tr: "Zemin kaplaması düzeltilmeli." },
    { en: "The ropes are loose.", alt: "Loose ropes.", ph: "Dı roops ar luus.", phs: "Luus roops.", tr: "İpler gevşek." },
    { en: "The canvas needs to be cleaned.", alt: "Canvas is dirty.", ph: "Dı kenvıs niidz tu bi kliind.", phs: "Kenvıs iz dörti.", tr: "Ring zeminin temizlenmesi gerekiyor." },
    { en: "The ropes need to be cleaned.", alt: "Ropes are dirty.", ph: "Dı roops niid tu bi kliind.", phs: "Roops ar dörti.", tr: "İplerin temizlenmesi gerekiyor." },
    { en: "The canvas is too wet and slippery.", alt: "Slippery canvas.", ph: "Dı kenvıs iz tuu vet end slipıri.", phs: "Slipıri kenvıs.", tr: "Ring zemini çok ıslak, kayıyor." },
  ],

  d2_hakem: [
    { en: "I don't feel well. May I rest?", alt: "Not feeling well. May I rest?", ph: "Ay doont fiil vel. Mey ay rest?", phs: "Not fiiling vel. Mey ay rest?", tr: "Kendimi iyi hissetmiyorum. Dinlenebilir miyim?" },
    { en: "I need to see a doctor.", alt: "Need a doctor.", ph: "Ay niid tu sii ey daktır.", phs: "Niid ey daktır.", tr: "Doktora görünmem gerekiyor." },
    { en: "I feel dizzy.", alt: "Dizzy.", ph: "Ay fiil dizi.", phs: "Dizi.", tr: "Başım dönüyor." },
    { en: "My arm hurts.", alt: "Arm hurts.", ph: "May arm herts.", phs: "Arm herts.", tr: "Kolum ağrıyor." },
    { en: "I feel nauseous.", alt: "Nauseous.", ph: "Ay fiil noojıs.", phs: "Noojıs.", tr: "Midem bulanıyor." },
    { en: "My foot hurts.", alt: "Foot hurts.", ph: "May fut herts.", phs: "Fut herts.", tr: "Ayağım ağrıyor." },
    { en: "My leg hurts.", alt: "Leg hurts.", ph: "May leg herts.", phs: "Leg herts.", tr: "Bacağım ağrıyor." },
    { en: "My hand hurts.", alt: "Hand hurts.", ph: "May hend herts.", phs: "Hend herts.", tr: "Elim acıyor." },
    { en: "My fingers hurt.", alt: "Fingers hurt.", ph: "May fingırz hert.", phs: "Fingırz hert.", tr: "Parmaklarım acıyor." },
    { en: "My blood sugar is low.", alt: "Low sugar.", ph: "May blad şugır iz loo.", phs: "Loo şugır.", tr: "Şekerim düştü." },
    { en: "My blood pressure is high.", alt: "High blood pressure.", ph: "May blad preşır iz hay.", phs: "Hay blad preşır.", tr: "Tansiyonum çıktı." },
    { en: "My blood pressure is low.", alt: "Low blood pressure.", ph: "May blad preşır iz loo.", phs: "Loo blad preşır.", tr: "Tansiyonum düştü." },
    { en: "I have a migraine.", alt: "Migraine.", ph: "Ay hev ey maygreyn.", phs: "Maygreyn.", tr: "Migren ağrım var." },
    { en: "I need to change my clothes.", alt: "Need to change.", ph: "Ay niid tu çeync may klooz.", phs: "Niid tu çeync.", tr: "Üstümü değiştirmem gerekiyor." },
    { en: "I lost my bow tie. Do you have any extra one?", alt: "Lost my bow tie. Have one?", ph: "Ay lost may boo tay. Duu yu hav eni ekstrı van?", phs: "Lost may boo tay. Hev van?", tr: "Papyonumu kaybettim. Fazladan papyonunuz var mı?" },
  ],
};

window.DAY2_QUIZ = [
  { sit: "Bir sporcunun eldivenleri hem onaysız hem de yıpranmış görünüyor.", q: "Ne söylersin?", opts: ["These gloves are not acceptable. Please change them.", "The gloves are loose. Please tape them.", "Only IFMA approved gloves are allowed.", "Can I see your gloves?"], c: 0, ex: "✓ 'These gloves are not acceptable. Please change them.' — hem onaysız hem hasarlı malzeme için 'not acceptable' kullanılır." },
  { sit: "Sporcu kaskını takmadan ringe çıkmaya hazırlanıyor.", q: "Ne söylersin?", opts: ["Put on your headguard.", "Remove your headguard.", "Can I see your headguard?", "Fix the headguard."], c: 0, ex: "✓ 'Put on your headguard.' — kask takma komutu." },
  { sit: "Sporcunun saç filesi yok, saçları dağınık.", q: "Ne söylersin?", opts: ["Please use a hair net.", "Please tuck your shirt into your shorts.", "Remove your headguard.", "The hijab must be white."], c: 0, ex: "✓ 'Please use a hair net.' — saç filesi zorunluluğu." },
  { sit: "Çok fazla vazelin sürülmüş, kurallara aykırı.", q: "Ne söylersin?", opts: ["Too much Vaseline. Please wipe it off.", "The gloves are loose. Please tape them.", "Please remove your jewelry.", "Show me your bandage."], c: 0, ex: "✓ 'Too much Vaseline. Please wipe it off.' — fazla vazelin uyarısı." },
  { sit: "Köşe görevlisi ceketiyle görev yerine geliyor.", q: "Ne söylersin?", opts: ["Please remove your jacket.", "Only sports shoes are allowed.", "Do not remove the gloves.", "Please take the water bottle."], c: 0, ex: "✓ 'Please remove your jacket.' — köşe görevlisinin ceketi çıkarması gerekiyor." },
  { sit: "Köşe görevlisi çok fazla su kullanıyor.", q: "Ne söylersin?", opts: ["Do not use too much water.", "Please take the water bottle.", "Please lean over the ropes.", "Please remove the towel."], c: 0, ex: "✓ 'Do not use too much water.' — su kullanım uyarısı." },
  { sit: "Köşe görevlisi havluyu almayı unuttu, süre dolmak üzere.", q: "Ne söylersin?", opts: ["Please remove the towel.", "Please lean over the ropes.", "Do not remove the gloves.", "Fix the headguard."], c: 0, ex: "✓ 'Please remove the towel.' — havlu kaldırma komutu." },
  { sit: "Sporcunun dişlik rengi yanlış — sarı gelmiş.", q: "Ne söylersin?", opts: ["The gum shield colour is not correct. It must be red or pink. Please change it.", "This gum shield is not acceptable. Please change it.", "Put in your gum shield.", "Can I see your gum shield?"], c: 0, ex: "✓ 'The gum shield colour is not correct. It must be red or pink. Please change it.' — renk kuralı ihlali." },
  { sit: "Aynı raundda 2 kere saydın, bunu Başhakeme bildiriyorsun.", q: "Ne söylersin?", opts: ["I counted twice in the same round.", "I counted twice in total.", "I gave two cautions.", "I counted three times in total."], c: 0, ex: "✓ 'I counted twice in the same round.' — aynı raundda sayma bildirimi." },
  { sit: "Sporcunun kasık koruyucusu yok, bunu raporluyorsun.", q: "Ne söylersin?", opts: ["The athlete has no groin guard.", "The athlete has no chest protector.", "The athlete has no bandage.", "The headguard is not approved."], c: 0, ex: "✓ 'The athlete has no groin guard.' — kasık koruyucu eksikliği bildirimi." },
  { sit: "Görevlendirildiğin ringi öğrenmek istiyorsun.", q: "Ne sorarsın?", opts: ["Which ring is it?", "Which bout number is it?", "What is my duty?", "Which weight division is it?"], c: 0, ex: "✓ 'Which ring is it?' — hangi ringde görev yapacağını öğrenmek için." },
  { sit: "Kaçıncı maçta görev yapacağını bilmiyorsun.", q: "Ne sorarsın?", opts: ["Which bout number is it?", "Which ring is it?", "May I check the duty list?", "Which category is it?"], c: 0, ex: "✓ 'Which bout number is it?' — maç numarasını öğrenmek için." },
  { sit: "Skor kartın bitti, yenisine ihtiyacın var.", q: "Ne söylersin?", opts: ["The scorecard is finished.", "I need a pen, please.", "Please step back.", "I pressed the wrong button."], c: 0, ex: "✓ 'The scorecard is finished.' — skor kartı bittiğinde bildirim." },
  { sit: "Yanlış köşeye puan verdiğini fark ettin.", q: "Ne söylersin?", opts: ["I gave the point to the wrong corner.", "I pressed the wrong button.", "I reset the score by mistake.", "I did not press the button."], c: 0, ex: "✓ 'I gave the point to the wrong corner.' — yanlış köşeye puan verme hatası." },
  { sit: "Zaman hakemi olarak sisteminiz durdu.", q: "Ne söylersin?", opts: ["The system has stopped.", "There is no sound.", "I stopped the time.", "I started the time."], c: 0, ex: "✓ 'The system has stopped.' — sistem arızası bildirimi." },
  { sit: "Zaman hakemi olarak zil sesi gelmiyor.", q: "Ne söylersin?", opts: ["There is no sound.", "The system has stopped.", "I stopped the time.", "I started the time."], c: 0, ex: "✓ 'There is no sound.' — ses problemi bildirimi." },
  { sit: "Bir sonraki maçı anons edeceksin, sporcuları hazırlığa çağırıyorsun.", q: "Hangi cümleyi kullanırsın?", opts: ["Next bout, red corner [Name] from [Country], blue corner [Name] from [Country], please get ready.", "Ring A, Bout number 2, red corner to the ring!", "This is the final call!", "Seconds out!"], c: 0, ex: "✓ 'Next bout... please get ready.' — maç öncesi hazırlık anons cümlesi." },
  { sit: "Kırmızı köşeyi ringe çağırıyorsun, A ringinde 3. maç.", q: "Ne söylersin?", opts: ["Ring A, Bout number 3, red corner [Name] from [Country] to the ring area!", "Ring A, Bout number 3, blue corner to the ring!", "Next bout, get ready.", "This is the final call!"], c: 0, ex: "✓ 'Ring A, Bout number 3, red corner... to the ring area!' — ringe çağırma anons cümlesi." },
  { sit: "Sporcu ringe gelmedi, son kez çağırıyorsun.", q: "Ne söylersin?", opts: ["This is the final call!", "Seconds out!", "The bouts are paused for one hour.", "Next bout, get ready."], c: 0, ex: "✓ 'This is the final call!' — son çağrı anons cümlesi." },
  { sit: "Maç başlamadan önce orta hakem olarak sporcuları ortaya çağırıyorsun.", q: "Ne söylersin?", opts: ["Red, Blue, come to the center. Shake hands. Good luck.", "Put on your headguard. Listen to my commands.", "This is your first caution.", "Will you continue?"], c: 0, ex: "✓ 'Red, Blue, come to the center. Shake hands. Good luck.' — maç başlangıç protokolü." },
  { sit: "Sporcu aynı raundda ikinci kez kurala aykırı hareket yaptı, son uyarısını veriyorsun.", q: "Ne söylersin?", opts: ["This is your last caution.", "This is your second caution.", "This is your first caution.", "Warning for unsportsmanlike behaviour."], c: 0, ex: "✓ 'This is your last caution.' — son uyarı bildirimi." },
  { sit: "Sporcu maç sırasında konuşuyor.", q: "Ne söylersin?", opts: ["Do not talk during the fight.", "No shaking hands during the fight.", "Calm down. No talking.", "Useless or aggressive utterance is not allowed."], c: 0, ex: "✓ 'Do not talk during the fight.' — maç içi konuşma yasağı." },
  { sit: "Sporcu kasıtlı olarak dişliğini çıkarttı, ceza veriyorsun.", q: "Jüriye ne bildirirsin?", opts: ["Warning for removing the gum shield.", "Warning for spitting.", "Warning for wrestling.", "Warning for biting."], c: 0, ex: "✓ 'Warning for removing the gum shield.' — dişlik cezası bildirimi." },
  { sit: "Sporcu iplerden destek alarak vuruş yapıyor.", q: "Ne söylersin?", opts: ["Striking while holding the ropes is not allowed.", "Do not use the ropes unfairly.", "Pushing forward more than two steps without striking is not allowed.", "Tackling the opponent's body or legs is not allowed."], c: 0, ex: "✓ 'Striking while holding the ropes is not allowed.' — ipleri tutarak vuruş yasağı." },
  { sit: "Yoot komutundan sonra sporcu vuruşuna devam etti.", q: "Ne söylersin?", opts: ["Striking after the round has ended is not allowed. Listen to me!", "You must follow the YOOT or YAEK command immediately.", "No shaking hands during the fight.", "Intentionally falling to avoid a hit is not allowed. Fight!"], c: 0, ex: "✓ 'Striking after the round has ended is not allowed. Listen to me!' — Yoot sonrası vuruş yasağı." },
  { sit: "Maç puanla sonuçlandı, kırmızı köşe kazandı.", q: "Karar kısaltması ve anons cümlesi hangisi?", opts: ["WP — Winner is Red corner.", "RSC-S — Winner is Red corner.", "KO-H — Winner is Red corner.", "DQ — Winner is Red corner."], c: 0, ex: "✓ 'WP — Winner is Red corner.' — puanla kazanma kararı." },
  { sit: "Sporcu başına ağır darbe aldı, hakem maçı durdurdu.", q: "Karar kısaltması hangisi?", opts: ["RSC-H", "RSC-B", "RSC-I", "KO-B"], c: 0, ex: "✓ RSC-H — Referee Stops Contest, Head Strike. Kafaya alınan ağır darbe nedeniyle durdurma." },
  { sit: "Sporcunun burnu kanıyor, doktora bildiriyorsun.", q: "Ne söylersin?", opts: ["The athlete's nose is bleeding.", "The athlete took a heavy strike to the head.", "The athlete fainted.", "The athlete vomited."], c: 0, ex: "✓ 'The athlete's nose is bleeding.' — burun kanaması bildirimi." },
  { sit: "Doktor ringe girmek istiyor ama henüz izin verilmedi.", q: "Ne söylersin?", opts: ["Please do not enter the ring.", "You may enter the ring.", "Can the athlete continue?", "What is the situation?"], c: 0, ex: "✓ 'Please do not enter the ring.' — doktoru durdurma komutu." },
  { sit: "Ring zemininde kayma var, zeminin temizlenmesi gerekiyor.", q: "Ne söylersin?", opts: ["The canvas is too wet and slippery.", "The canvas needs to be cleaned.", "The ropes are loose.", "The canvas needs to be fixed."], c: 0, ex: "✓ 'The canvas is too wet and slippery.' — kaygan zemin bildirimi." },
  { sit: "Başın dönüyor, görevini devredemezsin ama durumunu bildirmen gerekiyor.", q: "Ne söylersin?", opts: ["I feel dizzy.", "I don't feel well. May I rest?", "I need to see a doctor.", "My blood pressure is high."], c: 0, ex: "✓ 'I feel dizzy.' — baş dönmesi bildirimi." },
];
