// =================================================================
// ─── TMF MUAYTHAI HAKEM EĞİTİM MODÜLÜ - DAY 2 VERİ HAVUZU ────────
// =================================================================

window.DAY2_PHRASES = {
  // ─── JURY SEKMELERİ ────────────────────────────────────────────
  d2_juri_rap: [
    { en: "The protest has been officially rejected by the Jury.", ph: "Dı protest hes bin ofisıli ricektid bay dı curi.", tr: "İtiraz, Jüri tarafından resmi olarak reddedilmiştir." },
    { en: "The decision of the Referee is sustained.", ph: "Dı desizın ov dı referi iz sasteynd.", tr: "Orta hakemin kararı onanmıştır (geçerlidir)." },
    { en: "Please review the official scorecards from the last round.", ph: "Pliz rivyû dı ofisıl skorkards fram dı last raund.", tr: "Lütfen son raundun resmi puan kartlarını inceleyin." }
  ],
  d2_juri_diy: [
    { en: "Jury, are all judges ready for the next bout?", ph: "Curi, ar ol cadcız redi for dı nekst baut?", tr: "Jüri, sonraki maç için tüm yan hakemler hazır mı?" },
    { en: "We need a final clarification on this technical issue.", ph: "Vi nid a faynıl klerifikeysın on dis teknik isyû.", tr: "Bu teknik konuda son bir netleştirmeye ihtiyacımız var." }
  ],
  d2_juri_gov: [
    { en: "You are assigned as the Referee for bout number five.", ph: "Yu ar esaynd ez dı referi for baut nambır fayv.", phs: "Esaynd ez referi for baut fayv.", alt: "Assigned as Referee for bout five.", tr: "Beş numaralı maç için orta hakem olarak görevlendirildiniz." },
    { en: "Please check your seat number on the duty list.", ph: "Pliz cek yor sit nambır on dı dyûti list.", tr: "Lütfen görev listesindeki koltuk numaranızı kontrol edin." }
  ],
  d2_hakem: [
    { en: "The referee requires medical attention. Call the doctor.", ph: "Dı referi rikuayırz medikıl atenşın. Kol dı doktır.", tr: "Hakemin tıbbi müdahaleye ihtiyacı var. Doktoru çağırın." },
    { en: "I am feeling dizzy and cannot continue my duty.", ph: "Ay em filing dizi end kennot kontinye mi dyûti.", tr: "Başım dönüyor ve görevime devam edemiyorum." }
  ],
  d2_ring: [
    { en: "The canvas is too slippery. It must be wiped immediately.", ph: "Dı kenvıs iz tû slipıri. İt mast bi vaypt imidyıtli.", tr: "Ring zemini çok kaygan. Derhal silinmesi gerekiyor." },
    { en: "The ring ropes are loose. Please tighten them.", ph: "Dı ring rops ar lûs. Pliz taytın dem.", tr: "Ring ipleri gevşek. Lütfen onları sıkılaştırın." }
  ],

  // ─── EQUIPMENT SEKMELERİ ───────────────────────────────────────
  d2_ekipman: [
    { en: "Show me your hand wraps and bandage, please.", ph: "Şov mi yor hend reps end bendıc, pliz.", alt: "Show me your bandage.", phs: "Şov mi yor bendıc.", tr: "Lütfen el sargılarınızı (bandajlarınızı) bana gösterin." },
    { en: "The groin guard is mandatory for this category.", ph: "Dı groyn gard iz mendıtori for dis kategri.", tr: "Bu kategori için kasık koruyucu (kupa) zorunludur." },
    { en: "Your headguard is too loose. Please adjust it.", ph: "Yor hedgard iz tû lûs. Pliz ecast it.", alt: "Adjust the headguard.", phs: "Ecast dı hedgard.", tr: "Kaskınız çok gevşek. Lütfen ayarlayın." },
    { en: "The shin guards must be IFMA approved.", ph: "Dı şin gards mast bi ifma apruvd.", tr: "Kaval koruyucular IFMA onaylı olmak zorundadır." }
  ],
  d2_kose: [
    { en: "Only two seconds are allowed in the corner.", ph: "Onli tû sekınds ar alavd in dı kornır.", tr: "Köşede sadece iki yardımcı antrenöre izin verilir." },
    { en: "Seconds, step down! Outside the ring, please.", ph: "Sekınds, step davn! Autsayd dı ring, pliz.", alt: "Seconds out!", phs: "Sekınds aut!", tr: "Yardımcılar aşağı insin! Ring dışına lütfen." },
    { en: "Do not touch the ropes during the round.", ph: "Du not tac dı rops dürink dı raund.", tr: "Raund boyunca iplere dokunmayın." }
  ],

  // ─── REFEREE SEKMELERİ ─────────────────────────────────────────
  d2_orta: [
    { en: "Chok! Clear out and separate!", ph: "Cok! Klir aut end sepıreyt!", alt: "Chok!", phs: "Cok!", tr: "Çok! Ayrılın ve geri çekilin! (Boksörleri ayırma komutu)" },
    { en: "Yut! Stop fighting immediately!", ph: "Yut! Stop faytink imidyıtli.", alt: "Yut!", phs: "Yut!", tr: "Yut! Dövüşü derhal durdurun!" },
    { en: "Chok! Break the clinch and fight!", ph: "Cok! Breyk dı klinc end fayt!", alt: "Chok!", phs: "Cok!", tr: "Çok! Sarılmayı bırakın ve dövüşün!" }
  ],
  d2_uyari: [
    { en: "Caution! No holding the ropes!", ph: "Kooşın! No holdink dı rops!", alt: "No holding ropes!", phs: "No holdink rops!", tr: "Sözlü Uyarı! İpleri tutmak yasak!" },
    { en: "Caution! Keep your head up down there!", ph: "Kooşın! Kip yor hed ap davn der.", alt: "Head up!", phs: "Hed ap!", tr: "Sözlü Uyarı! Kafanı aşağı eğme, yukarıda tut!" },
    { en: "Caution! No low strikes, keep it clean.", ph: "Kooşın! No lo strayks, kip it klir.", alt: "No low blows!", phs: "No lo blos!", tr: "Sözlü Uyarı! Bel altı (alçak) vuruş yok, temiz dövüşün." }
  ],
  d2_ceza: [
    { en: "Warning for the red corner! Headbutting is illegal.", ph: "Vornink for dı red kornır! Hedbatink iz iligıl.", alt: "Warning, red corner!", phs: "Vornink, red kornır!", tr: "Kırmızı köşeye resmi ceza (ihtar)! Kafa atmak yasaktır." },
    { en: "Warning for the blue corner! No striking after the command.", ph: "Vornink for dı blû kornır! No straykink aftır dı komend.", alt: "Warning, blue corner!", phs: "Vornink, blû kornır!", tr: "Mavi köşeye resmi ceza! Komuttan sonra vurmak yasaktır." }
  ],
  d2_karar: [
    { en: "The winner by Technical Knockout, in the blue corner!", ph: "Dı vinır bay teknik nakaut, in dı blû kornır!", alt: "Winner by TKO, blue corner!", phs: "Vinır bay ti-key-o, blû kornır!", tr: "Teknik Nakavt ile kazanan, mavi köşede!" },
    { en: "The winner by Unanimous Decision, red corner!", ph: "Dı vinır bay yûnenimıs desizın, red kornır!", alt: "Winner by decision, red!", phs: "Vinır bay desizın, red!", tr: "Oy birliği kararıyla kazanan, kırmızı köşe!" }
  ],
  d2_doktor: [
    { en: "Doctor, please check the cut on the athlete's eyebrow.", ph: "Doktır, pliz cek dı kat on dı etlits aybrau.", alt: "Doctor, check the cut.", phs: "Doktır, cek dı kat.", tr: "Doktor, lütfen sporcunun kaşındaki açılmayı (kesiği) kontrol edin." },
    { en: "The doctor declares the athlete unfit to continue.", ph: "Dı doktır deklers dı etlit unfit tu kontinye.", tr: "Doktor, sporcunun devam etmek için uygun olmadığını (dövüşemeyeceğini) bildiriyor." }
  ],
  d2_tayca: [
    { en: "Nueng, Song, Sam, Si, Ha, Hok, Chet, Paet, Kao, Sip.", ph: "Nıng, Song, Sam, Si, Ha, Hok, Cet, Pet, Kao, Sip.", tr: "1, 2, 3, 4, 5, 6, 7, 8, 9, 10. (Tayca Sayma Düzeni)" }
  ],

  // ─── JUDGE SEKMELERİ ───────────────────────────────────────────
  d2_yan: [
    { en: "The score for this round is ten to nine.", ph: "Dı skor for dis raund iz ten tu nayn.", tr: "Bu raundun skoru ona dokuzdur (10-9)." },
    { en: "Red corner dominated the round with effective knee strikes.", ph: "Red kornır domineytid dı raund vit efektiv ni strayks.", tr: "Kırmızı köşe, etkili diz vuruşlarıyla raundu domine etti." }
  ],
  d2_skor: [
    { en: "Please enter the points into the electronic scoring system.", ph: "Pliz entır dı poynts intu dı elektronik skorink sistım.", tr: "Lütfen puanları elektronik skor sistemine girin." },
    { en: "The score sheets must be signed before submission.", ph: "Dı skor sits mast bi saynd bifor sabmisın.", tr: "Skor kağıtları teslim edilmeden önce imzalanmalıdır." }
  ],

  // ─── TIMEKEEPER SEKMELERİ ──────────────────────────────────────
  d2_zaman: [
    { en: "Ring the bell to start the first round.", ph: "Rink dı bel tu start dı först raund.", tr: "Birinci raundu başlatmak için zili çalın." },
    { en: "Stop the clock! Time out requested by the Referee.", ph: "Stop dı klok! Taym aut rikuayrstid bay dı referi.", tr: "Süreyi durdurun! Orta hakem mola talep etti." }
  ],

  // ─── ANNOUNCER SEKMELERİ ───────────────────────────────────────
  d2_anons: [
    { en: "Ladies and gentlemen, welcome to the IFMA World Championships.", ph: "Leydiz end centılmın, velkam tu dı ifma vörld cempıyonsips.", tr: "Bayanlar baylar, IFMA Dünya Şampiyonası'na hoş geldiniz." },
    { en: "Representing the red corner, from Thailand!", ph: "Reprizentink dı red kornır, fram taylend!", tr: "Kırmızı köşeyi temsil ediyor, Tayland'dan!" }
  ]
};

// ─── 3. JURY SENARYO PRATİĞİ SORULARI (39 ADET) ───────────────────
window.QUIZ_JURY = [
  { en: "During a round, you gave a knock-down count to the same athlete two times. If requested, you report the count status to the Jury.", tr: "Bir raund içinde aynı sporcuya iki kez nakavt sayımı (knock-down count) yaptın. Talep edildiği takdirde; sayma durumunu jüriye rapor ediyorsun.", q: "Ne söylersin?", opts: ["I counted twice in the same round/ Two counts, same round.", "I counted twice in total/ Two counts total.", "I counted once in the same round/One count, same round.", "I gave two cautions."], c: 0, ex: "✓ 'Two counts, same round.' — Aynı raund içinde iki kez saydım." },
  { en: "An athlete receives their third count within a single round. If requested, you report the count status to the jury.", tr: "Bir sporcu tek bir raund içinde üçüncü kez sayma aldı. Talep edildiği takdirde; sayma durumunu jüriye rapor ediyorsun.", q: "Ne söylersin?", opts: ["I counted three times in the same round.", "I counted three times in total.", "Three counts total.", "I gave three cautions."], c: 0, ex: "✓ 'I counted three times in the same round.' — Aynı raund içinde üç kez saydım." },
  { en: "You issued two cautions to the red corner during the bout. If requested, you report the count status to the Jury.", tr: "Maç esnasında kırmızı köşeye iki resmi sözlü uyarı verdin. Talep edildiği takdirde; sayma durumunu jüriye rapor ediyorsun.", q: "Ne söylersin?", opts: ["I gave two cautions.", "Two counts total.", "I gave three cautions.", "Two counts, same round."], c: 0, ex: "✓ 'I gave two cautions.' — İki uyarı verdim." },
  { en: "During the glove check at the ring entrance, you notice the athlete has no hand wraps under their gloves. Report this violation to the Jury.", tr: "Ring girişindeki eldiven kontrolünde sporcunun eldivenlerinin altında bandaj olmadığını fark ediyorsun. Bu ihlali jüriye rapor ediyorsun.", q: "Ne söylersin?", opts: ["The athlete has no bandage.", "This bandage is not acceptable. Please change it.", "Show me your bandage.", "No groin guard."], c: 0, ex: "✓ 'The athlete has no bandage.' — Sporcunun bandajı yok." },
  { en: "You need to ask the jury if the second is permitted to replace a faulty headguard.", tr: "Köşe Görevlisinin kusurlu bir kaskı değiştirmesine izin verilip verilmediğini jüriye sorman gerekiyor.", q: "Ne söylersin?", opts: ["Can they change the headguard?", "Can I see your headguard?", "Show me your bandage.", "Headguard not approved. Must be changed."], c: 0, ex: "✓ 'Can they change the headguard?' — Kaskı değiştirebilirler mi?" },
  { en: "You need a tape to secure an athlete's equipment. Ask the Jury for assistance.", tr: "Bir sporcunun ekipmanını sabitlemek için banda ihtiyacın var. Jüriden yardım istiyorsun.", q: "Ne söylersin?", opts: ["Can you give me a tape?", "Tape the gloves.", "The gloves are loose. Please tape them.", "Can you give me a hair net?"], c: 0, ex: "✓ 'Can you give me a tape?' — Bana bir bant verebilir misiniz?" },
  { en: "A female athlete comes to the ring wearing a black hijab. Report this immediately to the Jury.", tr: "Bir kadın sporcu ringe siyah hicapla geliyor. Bunu derhal jüriye rapor ediyorsun.", q: "Ne söylersin?", opts: ["The hijab/body suit must be white.", "Can you give me a tape?", "This shirt is not approved. Please change it.", "Can you give me a hair net?"], c: 0, ex: "✓ 'The hijab/body suit must be white.' — Hicap/vücut giysisi beyaz olmalıdır." },
  { en: "During the pre-fight, you learned the athlete is missing their groin guard. Report this immediately to the Jury.", tr: "Maç öncesi sporcunun kasık koruyucusunun olmadığını öğreniyorsun. Bunu derhal jüriye rapor ediyorsun.", q: "Ne söylersin?", opts: ["The athlete has no groin guard.", "The athlete has no chest protector.", "Do you have a groin guard?", "The athlete's hijab is not approved."], c: 0, ex: "✓ 'The athlete has no groin guard.' — Sporcunun kasık koruması yok." },
  { en: "You inspect the athlete's body protection and see it is not IFMA approved. Inform the Jury that a replacement is mandatory.", tr: "Sporcunun gövde koruyucusunu inceliyorsun ve IFMA onaylı olmadığını görüyorsun. Değiştirilmesinin zorunlu olduğunu jüriye bildiriyorsun.", q: "Ne söylersin?", opts: ["Chest protector not approved. Must be changed.", "The chest protector is not approved. It must be changed.", "The athlete has no chest protector.", "Do you have a chest protector?"], c: 0, ex: "✓ 'Chest protector not approved. Must be changed.' — Göğüs koruyucu onaylı değil, değişmeli." },
  { en: "You need to leave the field of play briefly to use the toilet. Ask the Protocol Jury for permission.", tr: "Tuvaleti kullanmak için müsabaka alanından kısa süreliğine ayrılmanız gerekiyor. Protokol Jürisinden izin istiyorsunuz.", q: "Ne söylersin?", opts: ["May I go to the restroom?", "I need to make a phone call. May I?", "Can you help me, please?", "Which number should I go to?"], c: 0, ex: "✓ 'May I go to the restroom?' — Tuvalete gidebilir miyim?" },
  { en: "You must contact someone by phone. Ask the Protocol Jury for permission.", tr: "Telefonla birine ulaşmanız gerekiyor. Protokol Jürisinden izin istiyorsunuz.", q: "Ne söylersin?", opts: ["I need to make a phone call. May I?", "Thank you for your understanding.", "May I go to the restroom?", "Can you help me, please?"], c: 0, ex: "✓ 'I need to make a phone call. May I?' — Telefon araması yapabilir miyim?" },
  { en: "The Jury points out a small positioning mistake you made in the last round. Acknowledge the feedback and state that you will be careful.", tr: "Jüri son raundda yaptığınız küçük bir pozisyon hatasına dikkat çekiyor. Geri bildirimi kabul edip dikkat edeceğinizi belirtiyorsunuz.", q: "Ne söylersin?", opts: ["Thank you for your feedback. I will be careful.", "Thank you for your understanding.", "Can you help me, please?", "I need to make a phone call. May I?"], c: 0, ex: "✓ 'Thank you for your feedback. I will be careful.' — Geri bildiriminiz için teşekkürler, dikkat edeceğim." },
  { en: "You accidentally miscalculated a score or count, and the Jury corrects you. Apologize for your fault and assure them you'll pay attention.", tr: "Yanlışlıkla bir skoru veya saymayı hatalı hesapladınız ve Jury sizi düzeltti. Hatanız için özür dileyip dikkat edeceğinizi garanti ediyorsunuz.", q: "Ne söylersin?", opts: ["I am sorry for my mistake. I will be careful.", "What is my duty?", "Thank you for your understanding.", "I can help you."], c: 0, ex: "✓ 'I am sorry for my mistake. I will be careful.' — Hatam için özür dilerim, dikkat edeceğim." },
  { en: "You see another referee carrying heavy equipment or struggling with a task at the table. Offer your assistance.", tr: "Başka bir hakemin masada ağır ekipman taşıdığını veya bir görevde zorlandığını görüyorsunuz. Yardım teklif ediyorsunuz.", q: "Ne söylersin?", opts: ["I can help you.", "Can you help me, please?", "What is my duty?", "Which weight division is it?"], c: 0, ex: "✓ 'I can help you.' — Size yardım edebilirim." },
  { en: "You are told that you have an assignment, but you don't remember the specific role (e.g., judge or referee). Ask for clarification.", tr: "Size bir assignment (görev) verildiği söylendi ancak tam olarak rolünüzü (yan hakem mi orta hakem mi) hatırlamıyorsunuz. Netleştirmek için soruyorsunuz.", q: "Ne söylersin?", opts: ["What is my duty?", "Which category is it?", "Which bout number is it?", "Which number should I go to?"], c: 0, ex: "✓ 'What is my duty?' — Görevim nedir?" },
  { en: "You are assigned as a Judge, but you don’t remember which specific judge chair (1, 2, 3, 4, or 5) you need to sit on. Ask.", tr: "Yan hakem olarak görevlendirildiniz ancak tam olarak kaç numaralı hakem sandalyesine (1, 2, 3, 4 veya 5) oturacağınızı hatırlamıyorsunuz. Soruyorsunuz.", q: "Ne söylersin?", opts: ["Which number should I go to?", "Which ring is it?", "Which bout number is it?", "My duty?"], c: 0, ex: "✓ 'Which number should I go to?' — Kaç numaraya (sandalyeye) geçmeliyim?" },
  { en: "You want to look at the official assignment list to see the referee duties. Ask for permission.", tr: "Hakem görevlendirmelerini görmek için resmi görevlendirme kağıdına bakmak istiyorsunuz. İzin istiyorsunuz.", q: "Ne söylersin?", opts: ["May I check the duty list?", "What is my duty?", "Which number should I go to?", "Which category is it?"], c: 0, ex: "✓ 'May I check the duty list?' — Görev listesini kontrol edebilir miyim?" },
  { en: "To prepare for your assignment, you want to know which category the upcoming match is in.", tr: "Görevine hazırlanmak için yaklaşan maçın hangi kategori olduğunu öğrenmek istiyorsun.", q: "Ne söylersin?", opts: ["Which category is it?", "Which weight division is it?", "Which bout number is it?", "Which division?"], c: 0, ex: "✓ 'Which category is it?' — Hangi kategori?" },
  { en: "You need to check the match order to know exactly when you need to be ready at the ring side. Ask for the specific bout number.", tr: "Tam olarak ne zaman ring kenarında hazır olmanız gerektiğini bilmek için maç sırasını kontrol etmeniz gerekiyor. Maç numarasını soruyorsunuz.", q: "Ne söylersin?", opts: ["Which bout number is it?", "Which ring is it?", "Which weight division is it?", "May I check the duty list?"], c: 0, ex: "✓ 'Which bout number is it?' — Maç (maç sırası) numarası kaç?" },
  { en: "An athlete receives a hard punch, and their nose starts bleeding significantly. While the doctor is checking, report the specific situation to the approaching jury official.", tr: "Bir sporcu sert bir yumruk alıyor ve burnu ciddi şekilde kanamaya başlıyor. Doktor kontrol ederken, yanınıza gelen jüri görevlisine bu durumu rapor ediyorsunuz.", q: "Ne söylersin?", opts: ["The athlete's nose is bleeding/Nose bleeding.", "The athlete took a heavy strike to the head.", "The athlete is down.", "The athlete vomited."], c: 0, ex: "✓ 'The athlete's nose is bleeding.' — Sporcunun burnu kanıyor." },
  { en: "An athlete gets caught with a massive high kick or spinning elbow to the head and knocked down. The doctor enters the ring; report the cause of injury to the jury.", tr: "Bir sporcu kafasına çok ağır bir yüksek tekme veya döner dirsek alıyor ve nakavt oluyor. Doktor ringe giriyor; jüriye sakatlığın nedenini rapor ediyorsunuz.", q: "Ne söylersin?", opts: ["The athlete took a heavy strike to the head/ Heavy head strike.", "The athlete vomited.", "The athlete took a heavy strike to the body/ Heavy body strike.", "The athlete fainted."], c: 0, ex: "✓ 'Heavy head strike.' — Kafaya ağır darbe aldı." },
  { en: "After an accidental low blow, the fighter drops to the canvas in severe pain. While waiting for the doctor, inform the technical officials about the exact location of the strike.", tr: "Yanlışlıkla atılan alçak vuruş sonrasında dövüşçü büyük bir acıyla yere düşüyor. Doktoru beklerken teknik görevlilere darbenin tam yerini bildiriyorsunuz.", q: "Ne söylersin?", opts: ["The athlete took a heavy strike to the groin/ Heavy groin strike.", "The athlete fainted.", "The athlete took a heavy strike to the body/ Heavy head strike.", "No strike to groin."], c: 0, ex: "✓ 'Heavy groin strike.' — Kasık bölgesine ağır darbe aldı." },
  { en: "A fighter is hit with a hard knee strike to the ribs and cannot stand up straight (KO). Report the condition to the Jury.", tr: "Bir dövüşçü kaburgalarına sert bir diz vuruşu alıyor ve dik duramıyor (KO). Jüriye durumu rapor ediyorsunuz.", q: "Ne söylersin?", opts: ["The athlete took a heavy strike to the body/Heavy body strike.", "The athlete fainted.", "The chest protector is not approved. It must be changed.", "The athlete took a heavy strike to the head."], c: 0, ex: "✓ 'Heavy body strike.' — Gövdeye (kaburgaya) ağır darbe aldı." },
  { en: "During the intense clinch or after a hard body shot, the athlete feels sick and throws up on the canvas. Turn to the Jury and state what happened.", tr: "Yoğun bir clinch esnasında veya sert bir gövde darbesinden sonra sporcu fenalaşıyor ve ring zeminine kusuyor. Jüriye dönüp ne olduğunu bildiriyorsunuz.", q: "Ne söylersin?", opts: ["The athlete vomited.", "Heavy head strike.", "The athlete fainted.", "Fainted."], c: 0, ex: "✓ 'The athlete vomited.' — Sporcu kustu." },
  { en: "An athlete takes a heavy knockout blow and loses consciousness completely on the floor. While the medical team is responding, report the status to the Jury.", tr: "Bir sporcu ağır bir nakavt darbesi alıyor ve yerde bilincini tamamen kaybediyor (bayılıyor). Sağlık ekibi müdahale ederken Jüriye durumu rapor ediyorsunuz.", q: "Ne söylersin?", opts: ["The athlete fainted.", "Nose bleeding.", "The athlete vomited.", "Heavy head strike."], c: 0, ex: "✓ 'The athlete fainted.' — Sporcu bayıldı/bilincini yitirdi." },
  { en: "You start feeling unwell during a long session and need to step away from your duty to rest. Inform the Jury.", tr: "Uzun bir seans sırasında kendinizi kötü hissetmeye başladınız ve dinlenmek için görevinizden kısa bir süre ayrılmanız gerekiyor. Jüriye durumu bildiriyorsunuz.", q: "Ne söylersin?", opts: ["I don't feel well. May I rest?", "Can you help me?", "I need to change.", "I lost my bow tie."], c: 0, ex: "✓ 'I don't feel well. May I rest?' — İyi hissetmiyorum. Dinlenebilir miyim?" },
  { en: "You experience a sudden, severe medical issue at the ring side and require professional medical assistance. State your need clearly.", tr: "Ring kenarında ani ve ciddi bir sağlık sorunu yaşadınız ve profesyonel tıbbi yardıma ihtiyacınız var. İhtiyacınızı jüriye net bir şekilde belirtiyorsunuz.", q: "Ne söylersin?", opts: ["I need to see a doctor.", "My leg hurts.", "My blood pressure is low.", "I have a migraine."], c: 0, ex: "✓ 'I need to see a doctor.' — Doktor görmem gerekiyor." },
  { en: "Your head spin, and you feel unstable on your feet. Report this specific sensation.", tr: "Başınız döndürüyor ve ayakta durmakta zorlanıyorsunuz. Bu özel durumu jüriye rapor ediyorsunuz.", q: "Ne söylersin?", opts: ["I feel dizzy.", "I feel nauseous.", "My leg hurts.", "I have a migraine."], c: 0, ex: "✓ 'I feel dizzy.' — Başım dönüyor." },
  { en: "After a close exchange where you had to split the athletes, you feel a sharp pain in your upper extremity and can’t continue to your duty. Inform the Jury.", tr: "Sporcuları ayırırken üst uzvunuzda (kolunuzda) keskin bir ağrı hissettiniz ve göreve devam edemiyorsunuz. Jüriye bilgi veriyorsunuz.", q: "Ne söylersin?", opts: ["My arm hurts. I can’t continue.", "My leg hurts. I can’t continue.", "Arm hurts. I can’t continue.", "My hand hurts. I can’t continue."], c: 0, ex: "✓ 'My arm hurts. I can't continue.' — Kolum ağrıyor, devam edemiyorum." },
  { en: "You start feeling dynamic stomach discomfort and feel like you might throw up. Inform the Jury immediately.", tr: "Dinamik bir mide rahatsızlığı hissetmeye başladınız ve kusacak gibi oluyorsunuz. Gözlemciye derhal bilgi veriyorsunuz.", q: "Ne söylersin?", opts: ["I feel nauseous.", "Arm hurts. I can’t continue.", "I feel dizzy.", "The athlete vomited."], c: 0, ex: "✓ 'I feel nauseous.' — Midem bulanıyor." },
  { en: "Your lower limb or foot is causing you severe pain. Report it.", tr: "Ayağınız size ciddi acı veriyor. Bunu rapor ediyorsunuz.", q: "Ne söylersin?", opts: ["My foot hurts.", "My leg hurts.", "I feel dizzy.", "My hand hurts."], c: 0, ex: "✓ 'My foot hurts.' — Ayağım ağrıyor." },
  { en: "You are feeling weak, shaky, and sweating. Report your glucose drop to the table.", tr: "Kendinizi halsiz, titrer vaziyette hissediyorsunuz. Şekerinizin düştüğünü masaya bildiriyorsunuz.", q: "Ne söylersin?", opts: ["My blood sugar is low.", "My foot hurts.", "My blood pressure is low.", "I feel dizzy."], c: 0, ex: "✓ 'My blood sugar is low.' — Kan şekerim düşük." },
  { en: "You notice your blood pressure is spiking, causing a pulsing feeling in your head. Inform the Jury about your hypertension.", tr: "Tansiyonunuzun yükseldiğini ve başınızda zonklama yarattığını fark ettiniz. Jüriye yüksek tansiyon durumunuzu bildiriyorsunuz.", q: "Ne söylersin?", opts: ["My blood pressure is high.", "I feel dizzy.", "My blood pressure is low.", "My blood sugar is low."], c: 0, ex: "✓ 'My blood pressure is high.' — Tansiyonum yüksek." },
  { en: "You realize your bow tie came off and is missing. Ask a colleague or Jury for a spare.", tr: "Ringe çağrılmadan hemen önce papyonunuzun çıktığını ve kaybolduğunu fark ettiniz. Bir meslektaşınızdan veya Jüriden yedek istiyorsunuz.", q: "Ne söylersin?", opts: ["I lost my bow tie. Do you have any extra one?", "My blood sugar is low.", "Headguard not approved. Must be changed.", "Do you have gloves?"], c: 0, ex: "✓ 'I lost my bow tie. Do you have any extra one?' — Papyonumu kaybettim, yedeğiniz var mı?" },
  { en: "You notice that the canvas fabric has unfastened from the corner or has dangerous folds that could trip the athletes. Inform the Jury.", tr: "Ring zemin kaplamasının köşeden çözüldüğünü veya sporcuların takılmasına neden olabilecek tehlikeli katlanmalar oluşturduğunu fark ediyorsun. Jüriye bildiriyorsunuz.", q: "Ne söylersin?", opts: ["The canvas needs to be fixed.", "The canvas needs to be cleaned.", "The canvas is too wet and slippery.", "Slippery canvas."], c: 0, ex: "✓ 'The canvas needs to be fixed.' — Ring zemini (brandası) sabitlenmeli/düzeltilmeli." },
  { en: "During a clinch, the athletes lean against the ring boundaries and the lines sag heavily, which is dangerous. Inform the Jury.", tr: "Clinch esnasında sporcular iplere yaslanıyor ve ipler çok fazla sarkıyor, bu durum tehlikelidir. Jüriye bildiriyorsunuz.", q: "Ne söylersin?", opts: ["The ropes are loose.", "Slippery canvas.", "The ropes need to be cleaned.", "Ropes are dirty."], c: 0, ex: "✓ 'The ropes are loose.' — İpler gevşek/sarkıyor." },
  { en: "There is dry dirt, or small debris on the ring floor that needs to be swept before the next bout. Request maintenance.", tr: "Bir sonraki maçtan önce ring zemininde süpürülmesi gereken kuru kir veya küçük kalıntılar var. Görevlilerden temizlik talep ediyorsunuz.", q: "Ne söylersin?", opts: ["The canvas needs to be cleaned.", "Ropes are dirty.", "The canvas needs to be fixed.", "The canvas is too wet and slippery."], c: 0, ex: "✓ 'The canvas needs to be cleaned.' — Ring zemininin temizlenmesi (süpürülmesi) gerekiyor." },
  { en: "An athlete's nosebleed has smeared all over the ring ropes. Request maintenance.", tr: "Bir sporcunun burun kanaması ring iplerinin her yerine bulaşmış. Görevlilerden temizlik talep ediyorsunuz.", q: "Ne söylersin?", opts: ["The ropes need to be cleaned.", "The ropes are loose.", "Loose ropes.", "The canvas needs to be fixed."], c: 0, ex: "✓ 'The ropes need to be cleaned.' — İplerin temizlenmesi gerekiyor." },
  { en: "The seconds poured too much water during the break, and now there is a large puddle on the floor causing athletes to lose traction. Request maintenance.", tr: "Yardımcılar mola esnasında çok fazla su döktü ve şu an yerde sporcuların kaymasına neden olan büyük bir su birikintisi var. Görevlilerden temizlik talep ediyorsunuz.", q: "Ne söylersin?", opts: ["The canvas is too wet and slippery.", "The canvas needs to be fixed.", "The ropes are loose.", "Canvas is dirty."], c: 0, ex: "✓ 'The canvas is too wet and slippery.' — Branda çok ıslak ve kaygan." }
];

// ─── 4. EQUIPMENT SENARYO PRATİĞİ SORULARI (27 ADET) ───────────────
window.QUIZ_EQUIPMENT = [
  { sit: "Bir sporcu onaylı olmayan eldivenlerle geliyor. Ona IFMA kuralını bildiriyorsun.", q: "Ne söylersin?", opts: ["Only IFMA approved gloves are allowed.", "Ankle protection is not allowed.", "The gloves must be 10 oz.", "Can I see your gloves?"], c: 0, ex: "✓ 'Only IFMA approved gloves are allowed.'" },
  { sit: "Sporcunun kaval koruyucularını inceliyorsun ve uygun olmadığını görüyorsun. Değiştirmesini söylüyorsun.", q: "Ne söylersin?", opts: ["These shin guards are not acceptable. Please change them.", "The shin guards are loose. Please tape them.", "Can I see your gloves?", "Ankle protection is not allowed."], c: 0, ex: "✓ 'These shin guards are not acceptable. Please change them.'" },
  { sit: "Sporcunun eldivenlerinin gevşek olduğunu ve döndüğünü fark ediyorsun. Ne yapması gerektiğini söylüyorsun.", q: "Ne söylersin?", opts: ["The gloves are loose. Please tape them.", "Can I see your gloves?", "The gloves must be 10 oz.", "Only IFMA approved gloves are allowed."], c: 0, ex: "✓ 'The gloves are loose. Please tape them.'" },
  { sit: "Sporcunun tişörtü şortunun dışına sarkıyor. Düzeltmesini söylüyorsun.", q: "Ne söylersin?", opts: ["Please tuck your shirt into your shorts.", "This shirt is not approved. Please change it.", "Please use a hair net.", "Too much Vaseline. Please wipe it off."], c: 0, ex: "✓ 'Please tuck your shirt into your shorts.'" },
  { sit: "Maç başlamadan önce ve selamlaşmadan sonra sporculara talimat veriyorsun.", q: "Ne söylersin?", opts: ["Put on your headguard.", "Put on your Mongkon.", "Show me your bandage.", "Can I see your headguard?"], c: 0, ex: "✓ 'Put on your headguard.'" },
  { sit: "Eldivenler takılmadan önce sporcunun ellerindeki bandajı kontrol etmen gerekiyor.", q: "Ne söylersin?", opts: ["Show me your bandage.", "This bandage is not acceptable. Please change it.", "Can I see your gloves?", "Do you have a groin guard?"], c: 0, ex: "✓ 'Show me your bandage.'" },
  { sit: "Sporcunun kaval koruyucusunun altına ayak bilek koruyucusu (çorap) taktığını fark ediyorsun ki bu kategoride yasak. Bildiriyorsun.", q: "Ne söylersin?", opts: ["Ankle protection is not allowed.", "These shin guards are not acceptable. Please change them.", "The shin guards are loose. Please tape them.", "Your toenails are too long. Please trim them."], c: 0, ex: "✓ 'Ankle protection is not allowed.'" },
  { sit: "Sporcunun uzun saçları kaskın dışına taşıyor. Yapması gerekeni söylüyorsun.", q: "Ne söylersin?", opts: ["Please use a hair net.", "Please tuck your shirt into your shorts.", "Put on your headguard.", "The hijab/body suit must be white."], c: 0, ex: "✓ 'Please use a hair net.'" },
  { sit: "Antrenör sporcunun yüzüne çok fazla vazelin sürmüş. Silmelerini söylüyorsun.", q: "Ne söylersin?", opts: ["Too much Vaseline. Please wipe it off.", "Put in your gum shield.", "This chest protector is not acceptable. Please change it.", "Your toenails are too long. Please trim them."], c: 0, ex: "✓ 'Too much Vaseline. Please wipe it off.'" },
  { sit: "Sporcu kırmızı veya pembe renk bir dişlikle geliyor ki bu yasaktır. Değiştirmesini söylüyorsun.", q: "Ne söylersin?", opts: ["This gum shield is not acceptable. Please change it.", "Can I see your gum shield?", "Put in your gum shield.", "Too much Vaseline. Please wipe it off."], c: 0, ex: "✓ 'This gum shield is not acceptable. Please change it.'" },
  { sit: "Sporcunun saç tokası taktığını fark ediyorsun. Çıkarmasını söylüyorsun.", q: "Ne söylersin?", opts: ["Please remove your hair clip. It is not allowed.", "Please use a hair net.", "Please remove your jewelry. It is not allowed.", "Remove your headguard."], c: 0, ex: "✓ 'Please remove your hair clip. It is not allowed.'" },
  { sit: "Sporcu kaskını takıp ortaya geliyor ama dişliğini takmayı unutmuş. Talimat veriyorsun.", q: "Ne söylersin?", opts: ["Put in your gum shield.", "Can I see your gum shield?", "Put on your headguard.", "Put on your Mongkon."], c: 0, ex: "✓ 'Put in your gum shield.'" },
  { sit: "Ekipman kontrolünde sporcuya kasık koruyucusu olup olmadığını soruyorsun.", q: "Ne söylersin?", opts: ["Do you have a groin guard?", "Do you have a chest protector?", "Ankle protection is not allowed.", "Show me your bandage."], c: 0, ex: "✓ 'Do you have a groin guard?'" },
  { sit: "Ekipman kontrolünde kadın sporcuya göğüs koruyucusu olup olmadığını soruyorsun.", q: "Ne söylersin?", opts: ["Do you have a chest protector?", "This chest protector is not acceptable. Please change it.", "Do you have a groin guard?", "This shirt is not approved. Please change it."], c: 0, ex: "✓ 'Do you have a chest protector?'" },
  { sit: "Sporcu siyah renkte bir hicap/vücut örtüsüyle gelmiş. Uygun olmadığını, beyaz giymesi gerektiğini söylüyorsun.", q: "Ne söylersin?", opts: ["The hijab/body suit must be white.", "This shirt is not approved. Please change it.", "Only IFMA approved gloves are allowed.", "These shorts are not approved. Please change them."], c: 0, ex: "✓ 'The hijab/body suit must be white.'" },
  { sit: "Sporcunun ayaklarını kontrol ediyorsun ve ayak tırnaklarının çok uzun olduğunu fark ediyorsun. Kesmelerini söylüyorsun.", q: "Ne söylersin?", opts: ["Your toenails are too long. Please trim them.", "Ankle protection is not allowed.", "Too much Vaseline. Please wipe it off.", "The shin guards are loose. Please tape them."], c: 0, ex: "✓ 'Your toenails are too long. Please trim them.'" },
  { sit: "Köşedeki yardımcı antrenörün sandalet veya terlik giydiğini fark ediyorsun. Ona kuralı bildiriyorsun.", q: "Ne söylersin?", opts: ["Only sports shoes are allowed.", "Please remove your jacket.", "Good luck.", "Please lean over the ropes."], c: 0, ex: "✓ 'Only sports shoes are allowed.'" },
  { sit: "Köşe görevlisi ağır bir ceket veya spor dışı bir kıyafet giyiyor. Çıkarmasını söylüyorsun.", q: "Ne söylersin?", opts: ["Please remove your jacket.", "Please remove the towel.", "Please remove the Prajiad.", "Fix the chest protector."], c: 0, ex: "✓ 'Please remove your jacket.'" },
  { sit: "Wai Kru bitti ve maçın başlama zamanı geldi. Köşeye kaskı takabileceklerini söylüyorsun.", q: "Ne söylersin?", opts: ["You may put on the headguard/Headguard on.", "You may remove the headguard/Headguard off.", "Put on your Mongkon/Mongkon on.", "Fix the headguard."], c: 0, ex: "✓ 'You may put on the headguard/Headguard on.'" },
  { sit: "Maç tamamen bitti. Köşe görevlilerine sporcunun kaskını çıkarabileceklerini söylüyorsun.", q: "Ne söylersin?", opts: ["You may remove the headguard/Headguard off.", "Remove your Mongkon.", "Do not remove the gloves.", "You may put on the headguard/Headguard on."], c: 0, ex: "✓ 'You may remove the headguard/Headguard off.'" },
  { sit: "Maç bitti ancak resmi karar henüz anons edilmedi. Bir yardımcı eldivenleri çözmeye çalışıyor. Onu durduruyorsun.", q: "Ne söylersin?", opts: ["Do not remove the gloves.", "Fix the gloves.", "Tape the gloves.", "Can I see your gloves?"], c: 0, ex: "✓ 'Do not remove the gloves.'" },
  { sit: "Raund başlıyor ve köşe görevlisi su şişesini ring zemininde unuttu. Almalarını söylüyorsun.", q: "Ne söylersin?", opts: ["Please take the water bottle.", "Do not use too much water.", "Please remove the towel.", "Fix the chest protector."], c: 0, ex: "✓ 'Please take the water bottle.'" },
  { sit: "Mola sırasında köşe görevlisi, sporcunun üstüne çok fazla su döküyor ve ring zeminini ıslatıyor. Onları uyarıyorsun.", q: "Ne söylersin?", opts: ["Do not use too much water.", "Please take the water bottle.", "Fix the elbow guard.", "Too much Vaseline. Please wipe it off."], c: 0, ex: "✓ 'Do not use too much water.'" },
  { sit: "Mola esnasında sporcunun dirsekliğinin kaydığını fark ediyorsun. Antrenöre düzeltmesini söylüyorsun.", q: "Ne söylersin?", opts: ["Fix the elbow guard.", "Tape the shin guards.", "Fix the chest protector.", "Please remove the Prajiad."], c: 0, ex: "✓ 'Fix the elbow guard.'" },
  { sit: "Maç esnasında sporcunun kaval koruyucuları sürekli dönüyor. Köşeye onları bantla sabitlemelerini söylüyorsun.", q: "Ne söylersin?", opts: ["Tape the shin guards.", "Tape the gloves.", "Fix the headguard.", "Fix the chest protector."], c: 0, ex: "✓ 'Tape the shin guards.'" },
  { sit: "Raund başlamadan hemen önce köşe iplerde bir havlu asılı bıraktı. Havluyu kaldırmalarını söylüyorsun.", q: "Ne söylersin?", opts: ["Please remove the towel.", "Please remove the Prajiad.", "Please lean over the ropes.", "Tape the gloves."], c: 0, ex: "✓ 'Please remove the towel.'" },
  { sit: "Ara esnasında yardımcılar iplerin arasından ringin içine uzanıyor. İplerin üstünden uzanmasını söylüyorsun.", q: "Ne söylersin?", opts: ["Please lean over the ropes.", "Please remove the towel.", "Step back.", "Tape the gloves."], c: 0, ex: "✓ 'Please lean over the ropes.'" }
];