// =================================================================
// ─── TMF MUAYTHAI HAKEM EGİTİM MODÜLÜ - DAY 2 VERİ HAVUZU ────────
// =================================================================

// ─── FIELD OF PLAY - Müsabaka Alanı Orijinal Verileri ──────────────
window.DAY2_PHRASES = {

  // ── JURY ──────────────────────────────────
  d2_juri_rap: [
    { en: "I counted once in the same round.", alt: "One count, same round.", ph: "Ay kauntıd vans in dı seym raund.", phs: "Van kaunt, seym raund.", tr: "Aynı raundda 1 kere saydım." },
    { en: "I counted twice in the same round.", alt: "Two counts, same round.", ph: "Ay kauntıd tways in dı seym raund.", phs: "Tuu kaunts, seym raund.", tr: "Aynı raundda 2 kere saydım." },
    { en: "I counted three times in the same round.", alt: "Three counts, same round.", ph: "Ay kauntıd thrii taymz in dı seym raund.", phs: "Thrii kaunts, seym raund.", tr: "Aynı raundda 3 kere saydım." },
    { en: "I counted twice in total.", alt: "Two counts total.", ph: "Ay kauntıd tways in tootıl.", phs: "Tuu kaunts tootıl.", tr: "Toplamda 2 kere saydım." },
    { en: "I counted three times in total.", alt: "Three counts total.", ph: "Ay kauntıd thrii taymz in tootıl.", phs: "Thrii kaunts tootıl.", tr: "Toplamda 3 kere saydım." },
    { en: "I geyv two cautions.", alt: "Two cautions.", ph: "Ay geyv tuu kooşınz.", phs: "Tuu kooşınz.", tr: "2 kere uyarı verdim." },
    { en: "I geyv three cautions.", alt: "Three cautions.", ph: "Ay geyv thrii kooşınz.", phs: "Thrii kooşınz.", tr: "3 kere uyarı verdim." },
    { en: "The athlete has no bandage.", alt: "No bandage.", ph: "Dı esliit haz noo bandıc.", phs: "Noo bandıc.", tr: "Sporcunun bandajı yok." },
    { en: "Can they change the headguard?", alt: "", ph: "Kan dey çeync dı hedgard?", phs: "", tr: "Kaskı değiştirebilirler mi?" },
    { en: "Can you give me a hair net?", alt: "Hair net, please.", ph: "Kan yu giv mi ey her net?", phs: "Her net, pliiz.", tr: "Saç filesi verir misiniz?" },
    { en: "Can you give me some tape?", alt: "Tape, please.", ph: "Kan yu giv mi sam teyp?", phs: "Teyp, pliiz.", tr: "Bant verebilir misiniz?" },
    { en: "The athlete's toenails are too long.", alt: "Toenails too long.", ph: "Dı esliits tooneylz ar tuu long.", phs: "Tooneylz tuu long.", tr: "Sporcunun ayak tırnakları uzun." },
    { en: "The athlete's hijab is not approved.", alt: "Hijab not acceptable.", ph: "Dı esliits hicab iz not ıpruuvd.", phs: "Hicab not ekseptibıl.", tr: "Sporcunun baş örtüsü uygun değil." },
    { en: "The athlete has no groin guard.", alt: "No groin guard.", ph: "Dı esliit haz noo groyn gard.", phs: "Noo groyn gard.", tr: "Sporcunun kasık koruyucusu yok." },
    { en: "The athlete has no chest protector.", alt: "No chest protector.", ph: "Dı esliit haz noo çest prıtektır.", phs: "Noo çest prıtektır.", tr: "Sporcunun göğüs koruyucusu yok." },
    { en: "The headguard is not approved. It must be changed.", alt: "Headguard not approved. Must be changed.", ph: "Dı hedgard iz not ıpruuvd. İt mast bi çeyncd.", phs: "Hedgard not ıpruuvd. Mast bi çeyncd.", tr: "Kask uygun değil, değiştirilmeli." },
    { en: "The gloves are not approved. They must be changed.", alt: "Gloves not approved. Must be changed.", ph: "Dı glavz ar not ıpruuvd. Dey mast bi çeyncd.", phs: "Glavz not ıpruuvd. Mast bi çeyncd.", tr: "Eldiven uygun değil, değiştirilmeli." },
    { en: "The elbow guard is not approved. It must be changed.", alt: "Elbow guard not approved. Must be changed.", ph: "Dı elboo gard iz not ıpruuvd. İt mast bi çeyncd.", phs: "Elboo gard not ıpruuvd. Mast bi çeyncd.", tr: "Dirseklik uygun değil, değiştirilmeli." },
    { en: "The chest protector is not approved. It must be changed.", alt: "Chest protector not approved. Must be changed.", ph: "Dı çest prıtektır iz not ıpruuvd. İt mast bi çeyncd.", phs: "Çest prıtektır not ıpruuvd. Mast bi çeyncd.", tr: "Göğüs koruyucu uygun değil, değiştirilmeli." },
    { en: "The athlete's nose is bleeding.", alt: "Nose bleeding.", ph: "Dı esliits nooz iz bliiding.", phs: "Nooz bliiding.", tr: "Sporcunun burnu kanıyor." },
    { en: "The athlete took a heavy strike to the head.", alt: "Heavy head strike.", ph: "Dı esliit tuk ey hevi strayk tu dı hed.", phs: "Hevi hed strayk.", tr: "Sporcu başına ağır darbe aldı." },
    { en: "The athlete took a heavy strike to the groin.", alt: "Heavy groin strike.", ph: "Dı esliit tuk ey hevi strayk tu dı groyn.", phs: "Hevi groyn strayk.", tr: "Sporcu kasığına ağır darbe aldı." },
    { en: "The athlete took a heavy strike to the body.", alt: "Heavy body strike.", ph: "Dı esliit tuk ey hevi strayk tu dı badi.", phs: "Hevi badi strayk.", tr: "Sporcu gövdesine ağır darbe aldı." },
    { en: "The athlete vomited.", alt: "Vomited.", ph: "Dı esliit vamitıd.", phs: "Vamitıd.", tr: "Sporcu kustu." },
    { en: "The athlete fainted.", alt: "Fainted.", ph: "Dı esliit feyntıd.", phs: "Feyntıd.", tr: "Sporcu bayıldı." },
  ],

  d2_juri_diy: [
    { en: "I need to make a phone call. May I?", alt: "", ph: "Ay niid tu meyk ey foon kool. Mey ay?", phs: "", tr: "Telefon görüşmesi yapmam gerekiyor. Gidebilir miyim?" },
    { en: "May I go to the restroom?", alt: "", ph: "Mey ay goo tu dı restruum?", phs: "", tr: "Lavaboya gidebilir miyim?" },
    { en: "Thank you for your understanding.", alt: "Thank you.", ph: "Thenk yu for yor andırstendıng.", phs: "Thenk yu.", tr: "Anlayışınız için teşekkür ederim." },
    { en: "Thank you for your feedback. I will be careful.", alt: "Thank you. I'll be careful.", ph: "Thenk yu for yor fiidbek. Ay vil bi kerful.", phs: "Thenk yu. Ayl bi kerful.", tr: "Geri bildiriminiz için teşekkür ederim. Dikkat edeceğim." },
    { en: "I am sorry for my mistake. I will be careful.", alt: "Sorry. I'll be careful.", ph: "Ay em sori for may misteyk. Ay vil bi kerful.", phs: "Sori. Ayl bi kerful.", tr: "Hatam için özür dilerim. Dikkat edeceğim." },
    { en: "I can help you.", alt: "I can help.", ph: "Ay kan help yu.", phs: "Ay kan help.", tr: "Yardım edebilirim." },
    { en: "Can you help me, please?", alt: "Help me, please.", ph: "Kan yu help mi, pliiz?", phs: "Help mi, pliiz.", tr: "Bana yardımcı olabilir misiniz?" },
  ],

  d2_juri_gov: [
    { en: "Do I have a duty?", alt: "Any duty for me?", ph: "Duu ay hav ey dyuuti?", phs: "Eni dyuuti for mi?", tr: "Görevim var mı?" },
    { en: "What is my duty?", alt: "My duty?", ph: "Vat iz may dyuuti?", phs: "May dyuuti?", tr: "Görevim nedir?" },
    { en: "Which number should I go to?", alt: "Which number?", ph: "Viç nambır şud ay goo tu?", phs: "Viç nambır?", tr: "Kaç numaraya geçeceğim?" },
    { en: "Which weight division is it?", alt: "Which division?", ph: "Viç veyt divıcın iz it?", phs: "Viç divıcın?", tr: "Hangi sıklet?" },
    { en: "Which category is it?", alt: "Which category?", ph: "Viç ketıgori iz it?", phs: "Viç ketıgori?", tr: "Hangi kategori?" },
    { en: "May I check the duty list?", alt: "", ph: "Mey ay çek dı dyuuti list?", phs: "", tr: "Görev listesine bakabilir miyim?" },
    { en: "Which bout number is it?", alt: "Which bout?", ph: "Viç baut nambır iz it?", phs: "Viç baut?", tr: "Kaçıncı maç?" },
    { en: "Which ring is it?", alt: "Which ring?", ph: "Viç ring iz it?", phs: "Viç ring?", tr: "Hangi ring?" },
  ],

  d2_hakem: [
    { en: "I don't feel well. May I rest?", alt: "Not feeling well. May I rest?", ph: "Ay doont fiil vel. Mey ay rest?", phs: "Not fiiling vel. Mey ay rest?", tr: "Kendimi iyi hissetmiyorum. Dinlenebilir miyim?" },
    { en: "I need to see a doctor.", alt: "Need a doctor.", ph: "Ay niid tu sii ey daktır.", phs: "Niid ey daktır.", tr: "Doktora görünmem gerekiyor." },
    { en: "I feel dizzy.", alt: "", ph: "Ay fiil dizi.", phs: "", tr: "Başım dönüyor." },
    { en: "My arm hurts.", alt: "", ph: "May arm herts.", phs: "", tr: "Kolum ağrıyor." },
    { en: "I feel nauseous.", alt: "", ph: "Ay fiil noojıs.", phs: "", tr: "Midem bulanıyor." },
    { en: "My foot hurts.", alt: "", ph: "May fut herts.", phs: "", tr: "Ayağım ağrıyor." },
    { en: "My leg hurts.", alt: "", ph: "May leg herts.", phs: "", tr: "Bacağım ağrıyor." },
    { en: "My hand hurts.", alt: "", ph: "May hend herts.", phs: "", tr: "Elim acıyor." },
    { en: "My fingers hurt.", alt: "", ph: "May fingırz hert.", phs: "", tr: "Parmaklarım acıyor." },
    { en: "My blood sugar is low.", alt: "Low sugar.", ph: "May blad şugır iz loo.", phs: "Loo şugır.", tr: "Şekerim düştü." },
    { en: "My blood pressure is high.", alt: "High blood pressure.", ph: "May blad preşır iz hay.", phs: "Hay blad preşır.", tr: "Tansiyonum çıktı." },
    { en: "My blood pressure is low.", alt: "Low blood pressure.", ph: "May blad preşır iz loo.", phs: "Loo blad preşır.", tr: "Tansiyonum düştü." },
    { en: "I have a migraine.", alt: "Migraine.", ph: "Ay hev ey maygreyn.", phs: "Maygreyn.", tr: "Migren ağrım var." },
    { en: "I need to change my clothes.", alt: "Need to change.", ph: "Ay niid tu çeync may klooz.", phs: "Niid tu çeync.", tr: "Üstümü değiştirmem gerekiyor." },
    { en: "I lost my bow tie. Do you have any extra one?", alt: "Lost my bow tie. Have one?", ph: "Ay lost may boo tay. Duu yu hav eni ekstrı van?", phs: "Lost my boo tay. Hev van?", tr: "Papyonumu kaybettim. Fazladan papyonunuz var mı?" },
  ],

  d2_ring: [
    { en: "The canvas needs to be fixed.", alt: "", ph: "Dı kenvıs niidz tu bi fikst.", phs: "", tr: "Zemin kaplaması düzeltilmeli." },
    { en: "The ropes are loose.", alt: "Loose ropes.", ph: "Dı roops ar luus.", phs: "Luus roops.", tr: "İpler gevşek." },
    { en: "The canvas needs to be cleaned.", alt: "Canvas is dirty.", ph: "Dı kenvıs niidz tu bi kliind.", phs: "Kenvıs iz dörti.", tr: "Ring zemininin temizlenmesi gerekiyor." },
    { en: "The ropes need to be cleaned.", alt: "Ropes are dirty.", ph: "Dı roops niid tu bi kliind.", phs: "Roops ar dörti.", tr: "İplerin temizlenmesi gerekiyor." },
    { en: "The canvas is too wet and slippery.", alt: "Slippery canvas.", ph: "Dı kenvıs iz tuu vet end slipıri.", phs: "Slipıri kenvıs.", tr: "Ring zemini çok ıslak, kayıyor." },
  ],

  // ── EQUIPMENT ─────────────────────────────
  d2_ekipman: [
    { en: "Only IFMA approved gloves are allowed.", alt: "IFMA gloves only.", ph: "Onli IFMA ıpruuvd glavz ar ılaud.", phs: "IFMA glavz onli.", tr: "Sadece IFMA onaylı eldivenlere izin verilir." },
    { en: "Please remove your jewelry. It is not allowed.", alt: "Jewelry off.", ph: "Pliiz rimuuv yor cuulri. İt iz not ılaud.", phs: "Cuulri of.", tr: "Lütfen takılarınızı çıkarın. Yasaktır." },
    { en: "The gloves are loose. Please tape them.", alt: "Tape the gloves.", ph: "Dı glavz ar luus. Pliiz teyp dem.", phs: "Teyp dı glavz.", tr: "Eldivenler gevşek. Lütfen bantlayın." },
    { en: "The shin guards are loose. Please tape them.", alt: "Tape the shin guards.", ph: "Dı şin gardz ar luus. Pliiz teyp dem.", phs: "Teyp dı şin gardz.", tr: "Kaval koruyucular gevşek. Lütfen bantlayın." },
    { en: "Please tuck your shirt into your shorts.", alt: "Tuck in your shirt.", ph: "Pliiz tak yor şört intu yor şorts.", phs: "Tak in yor şört.", tr: "Lütfen tişörtünüzü şortunuzun içine sokun." },
    { en: "Please use a hair net.", alt: "Hair net, please.", ph: "Pliiz yuuz ey her net.", phs: "Her net pliiz.", tr: "Lütfen saç filesi kullanın." },
    { en: "Put in your gum shield.", alt: "Gum shield in.", ph: "Put in yor gam şiild.", phs: "Gam şiild in.", tr: "Dişliğini tak." },
    { en: "Put on your headguard.", alt: "Headguard on.", ph: "Put on yor hedgard.", phs: "Hedgard on.", tr: "Kaskını tak." },
    { en: "Remove your headguard.", alt: "Headguard off.", ph: "Rimuuv yor hedgard.", phs: "Hedgard of.", tr: "Kaskını çıkar." },
    { en: "Put on your Mongkon.", alt: "Mongkon on.", ph: "Put on yor Mongkon.", phs: "Mongkon on.", tr: "Mongkon'unu tak." },
    { en: "Remove your Mongkon.", alt: "Mongkon off.", ph: "Rimuuv yor Mongkon.", phs: "Mongkon of.", tr: "Mongkon'unu çıkar." },
    { en: "Show me your bandage.", alt: "Bandage?", ph: "Şoo mi yor bandıc.", phs: "Bandıc?", tr: "Bandajını göster." },
    { en: "The gloves must be 10 oz.", alt: "10 oz gloves only.", ph: "Dı glavz mast bi ten auns.", phs: "Ten auns glavz onli.", tr: "Eldivenler 10 ons olmalı." },
    { en: "Can I see your gloves?", alt: "Gloves?", ph: "Kan ay sii yor glavz?", phs: "Glavz?", tr: "Eldivenlerini görebilir miyim?" },
    { en: "Can I see your headguard?", alt: "Headguard?", ph: "Kan ay sii yor hedgard?", phs: "Hedgard?", tr: "Kaskını görebilir miyim?" },
    { en: "Can I see your gum shield?", alt: "Gum shield?", ph: "Kan ay sii yor gam şiild?", phs: "Gam şiild?", tr: "Dişliğini görebilir miyim?" },
    { en: "Do you have a groin guard?", alt: "Groin guard?", ph: "Duu yu hav ey groyn gard?", phs: "Groyn gard?", tr: "Kasık koruyucunuz var mı?" },
    { en: "Do you have a chest protector?", alt: "Chest protector?", ph: "Duu yu hav ey çest prıtektır?", phs: "Çest prıtektır?", tr: "Göğüs koruyucunuz var mı?" },
    { en: "Ankle protection is not allowed.", alt: "No ankle protection.", ph: "Ankıl prıtekşın iz not ılaud.", phs: "Noo ankıl prıtekşın.", tr: "Ayak bilek koruyucusuna izin verilmez." },
    { en: "The hijab/body suit must be white.", alt: "White hijab/body suit only.", ph: "Dı hicab / badi suut mast bi vayt.", phs: "Vayt hicab / badi suut onli.", tr: "Hicap / Body suit beyaz olmalıdır." },
    { en: "Your toenails are too long. Please trim them.", alt: "Trim your toenails.", ph: "Yor tooneylz ar tuu long. Pliiz trim dem.", phs: "Trim yor tooneylz.", tr: "Ayak tırnaklarınız çok uzun. Lütfen kesin." },
    { en: "Too much Vaseline. Please wipe it off.", alt: "Wipe the Vaseline.", ph: "Tuu maç vazıliin. Pliiz vayp it of.", phs: "Vayp dı vazıliin.", tr: "Çok fazla Vazelin var. Lütfen silin." },
    { en: "These gloves are not acceptable. Please change them.", alt: "Not acceptable. Change, please.", ph: "Diiz glavz ar not akseptıbıl. Pliiz çeync dem.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu eldivenler uygun değil. Lütfen değiştirin." },
    { en: "These shin guards are not acceptable. Please change them.", alt: "Not acceptable. Change, please.", ph: "Diiz şin gardz ar not akseptıbıl. Pliiz çeync dem.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu kaval koruyucular uygun değil. Lütfen değiştirin." },
    { en: "This gum shield is not acceptable. Please change it.", alt: "Not acceptable. Change, please.", ph: "Dis gam şiild iz not akseptıbıl. Pliiz çeync it.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu dişlik uygun değil. Lütfen değiştirin." },
    { en: "This chest protector is not acceptable. Please change it.", alt: "Not acceptable. Change, please.", ph: "Dis çest prıtektır iz not akseptıbıl. Pliiz çeync it.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu göğüs koruyucu uygun değil. Lütfen değiştirin." },
    { en: "This headguard is not acceptable. Please change it.", alt: "Not acceptable. Change, please.", ph: "Dis hedgard iz not akseptıbıl. Pliiz çeync it.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu kask uygun değil. Lütfen değiştirin." },
    { en: "These shorts are not approved. Please change them.", alt: "Not approved. Change, please.", ph: "Diiz şorts ar not ıpruuvd. Pliiz çeync dem.", phs: "Not ıpruuvd. Çeync pliiz.", tr: "Bu şort onaylı değil. Lütfen değiştirin." },
    { en: "This shirt is not approved. Please change it.", alt: "Not approved. Change, please.", ph: "Dis şört iz not ıpruuvd. Pliiz çeync it.", phs: "Not ıpruuvd. Çeync pliiz.", tr: "Bu tişört onaylı değil. Lütfen değiştirin." },
    { en: "This bandage is not acceptable. Please change it.", alt: "Not acceptable. Change, please.", ph: "Dis bandıc iz not akseptıbıl. Pliiz çeync it.", phs: "Not akseptıbıl. Çeync pliiz.", tr: "Bu bandaj uygun değil. Lütfen değiştirin." },
  ],

  d2_kose: [
    { en: "Only sports shoes are allowed.", alt: "Sports shoes only.", ph: "Onli sports şuuz ar ılaud.", phs: "Sports şuuz onli.", tr: "Sadece spor ayakkabıya izin verilir." },
    { en: "Please remove your jacket.", alt: "Jacket off. Please.", ph: "Pliiz rimuuv yor cakıt.", phs: "Cakıt of. Pliiz.", tr: "Lütfen ceketinizi çıkarın." },
    { en: "You may put on the headguard.", alt: "Headguard on.", ph: "Yu mey put on dı hedgard.", phs: "Hedgard on.", tr: "Kaskı takabilirsiniz." },
    { en: "You may remove the headguard.", alt: "Headguard off.", ph: "Yu mey rimuuv dı hedgard.", phs: "Hedgard of.", tr: "Kaskı çıkarabilirsiniz." },
    { en: "Do not remove the gloves.", alt: "Gloves stay on.", ph: "Duu not rimuuv dı glavz.", phs: "Glavz stey on.", tr: "Eldivenleri çıkarmayın." },
    { en: "Good luck.", alt: "Good luck.", ph: "Gud lak.", phs: "Gud lak.", tr: "Başarılar dilerim." },
    { en: "Please take the water bottle.", alt: "Water bottle.", ph: "Pliiz teyk dı votır botıl.", phs: "Votır botıl.", tr: "Lütfen su şişesini alın." },
    { en: "Do not use too much water.", alt: "Less water.", ph: "Duu not yuuz tuu maç votır.", phs: "Les votır.", tr: "Çok fazla su kullanmayın." },
    { en: "Fix the elbow guard.", alt: "Fix the elbow guard.", ph: "Fiks dı elboo gard.", phs: "Fiks dı elboo gard.", tr: "Dirsekliği düzeltin." },
    { en: "Fix the headguard.", alt: "Fix the headguard.", ph: "Fiks dı hedgard.", phs: "Fiks dı hedgard.", tr: "Kaskı düzeltin." },
    { en: "Fix the gloves.", alt: "Fix the gloves.", ph: "Fiks dı glavz.", phs: "Fiks dı glavz.", tr: "Eldivenleri düzeltin." },
    { en: "Fix the chest protector.", alt: "Fix the chest protector.", ph: "Fiks dı çest prıtektır.", phs: "Fiks dı çest prıtektır.", tr: "Göğüs koruyucuyu düzeltin." },
    { en: "Tape the elbow guard.", alt: "Tape the elbow guard.", ph: "Teyp dı elboo gard.", phs: "Teyp dı elboo gard.", tr: "Dirsekliği bantlayın." },
    { en: "Tape the gloves.", alt: "Tape the gloves.", ph: "Teyp dı glavz.", phs: "Teyp dı glavz.", tr: "Eldivenleri bantlayın." },
    { en: "Tape the shin guards.", alt: "Tape the shin guards.", ph: "Teyp dı şin gardz.", phs: "Teyp dı şin gardz.", tr: "Kaval koruyucuları bantlayın." },
    { en: "Please remove the towel.", alt: "Towel away.", ph: "Pliiz rimuuv dı tauıl.", phs: "Tauıl evey.", tr: "Lütfen havluyu kaldırın." },
    { en: "Please lean over the ropes.", alt: "Over the ropes.", ph: "Pliiz liin ovır dı roops.", phs: "Ovır dı roops.", tr: "Lütfen iplerden dışarı eğilin." },
    { en: "The gum shield colour is not correct. It must be red or pink. Please change it.", alt: "Wrong colour. Change it.", ph: "Dı gam şiild kalır iz not korekt. İt mast bi red or pink. Pliiz çeync it.", phs: "Rong kalır. Çeync it.", tr: "Dişlik rengi doğru değil. Kırmızı veya pembe olmalı. Lütfen değiştirin." },
  ],

  // ── REFEREE ───────────────────────────────
  d2_orta: [
    { en: "Red, Blue, come to the center. Shake hands. Good luck. To your corners.", alt: "Center. Shake hands. Good luck. To your corners.", ph: "Red, Bluu, kam tu dı sentır. Şeyk hendz. Gud lak. Tu yor kornırs.", phs: "Sentır. Şeyk hendz. Gud lak. Tu yor kornırs.", tr: "Kırmızı, Mavi ortaya gelin. El sıkışın. Başarılar. Köşelerinize." },
    { en: "Put on your headguard.", alt: "Headguard on.", ph: "Put on yor hedgard.", phs: "Hedgard on.", tr: "Kaskınızı takın." },
    { en: "Listen to my commands.", alt: "Listen to me.", ph: "Lisın tu may kımandz.", phs: "Lisın tu mi.", tr: "Komutlarımı dinleyin." },
    { en: "Are you okay?", alt: "Okay?", ph: "Ar yu okey?", phs: "Okey?", tr: "İyi misin?" },
    { en: "Will you continue?", alt: "Continue?", ph: "Vil yu kantinyu?", phs: "Kantinyu?", tr: "Devam edecek misin?" },
    { en: "Do you not want to continue?", alt: "You don't want?", ph: "Duu yu not vant tu kantinyu?", phs: "Yu doont vant?", tr: "Devam etmek istemiyor musun?" },
    { en: "Stop the time.", alt: "TIME.", ph: "Sıtop dı taym.", phs: "TAYM.", tr: "Zamanı durdur." },
    { en: "Start the 2 minutes.", alt: "2 minutes.", ph: "Sırart dı tu minıts.", phs: "Tu minıts.", tr: "2 dakikayı başlat." },
  ],

  d2_uyari: [
    { en: "This is your first caution.", alt: "First caution.", ph: "Dis iz yor ferst kooşın.", phs: "Ferst kooşın.", tr: "Bu sana ilk uyarım." },
    { en: "This is your second caution.", alt: "Second caution.", ph: "Dis iz yor sekınd kooşın.", phs: "Sekınd kooşın.", tr: "Bu sana ikinci uyarım." },
    { en: "This is your last caution.", alt: "Last caution.", ph: "Dis iz yor lest kooşın.", phs: "Lest kooşın.", tr: "Bu sana son uyarım." },
    { en: "No shaking hands during the fight.", alt: "No shaking hands.", ph: "Noo şeyking hendz dyuuring dı fayt.", phs: "Noo şeyking hendz.", tr: "El sıkışma yok (raund içinde)." },
    { en: "Do not talk during the fight.", alt: "Don't talk.", ph: "Duu not took dyuuring dı fayt.", phs: "Doont took.", tr: "Konuşma." },
    { en: "Do not spit out your gum shield.", alt: "Don't spit the gum shield.", ph: "Duu not spit aut yor gam şiild.", phs: "Doont spit dı gam şiild.", tr: "Dişliğini çıkarma/tükürme." },
    { en: "Sweeping without Muaythai skill is not allowed.", alt: "No sweep.", ph: "Sviiping vidaut Muaytay skil iz not ılaud.", phs: "Noo sviip.", tr: "Muaythai tekniği olmadan süpürmek yasaktır." },
    { en: "Holding the neck and arm is not allowed.", alt: "No head-arm hold.", ph: "Holding dı nek end arm iz not ılaud.", phs: "Noo hed-arm hoold.", tr: "Kafa-kol yapmak yasaktır." },
    { en: "Headbutting is not allowed.", alt: "No headbutt.", ph: "Hedbating iz not ılaud.", phs: "Noo hedbat.", tr: "Kafa atmak yasaktır." },
    { en: "Pressing on the opponent's eyes with the thumb is not allowed.", alt: "No eye pressing.", ph: "Presıng on dı ıpoonınts ayz vid dı thamb iz not ılaud.", phs: "Noo ay presıng.", tr: "Baş parmakla göze baskı uygulamak yasaktır." },
    { en: "Intentionally removing or displacing equipment is not allowed.", alt: "Don't remove equipment.", ph: "İntenşınıli rimuuvıng or displeysıng ikvipmınt iz not ılaud.", phs: "Doont rimuuv ikvipmınt.", tr: "Ekipmanları kasıtlı çıkarmak/gevşetmek yasaktır." },
    { en: "Throwing an opponent using the hip is not allowed.", alt: "No hip throw.", ph: "Throoing en ıpoonınt yuuzıng dı hip iz not ılaud.", phs: "Noo hip throo.", tr: "Kalçadan fırlatmak yasaktır." },
    { en: "Tackling the opponent's body or legs is not allowed.", alt: "No tackling.", ph: "Teklıng dı ıpoonınts badi or legz iz not ılaud.", phs: "Noo tekling.", tr: "Rakibin vücuduna veya bacaklarına sarılmak yasaktır." },
    { en: "Immobilizing the opponent's legs is not allowed.", alt: "No leg lock.", ph: "İmoobılayzıng dı ıpoonınts legz iz not ılaud.", phs: "Noo leg lok.", tr: "Rakibin bacağını kilitlemek yasaktır." },
    { en: "Lifting an opponent by the body is not allowed.", alt: "No lifting.", ph: "Liftıng en ıpoonınt bay dı badi iz not ılaud.", phs: "Noo lifting.", tr: "Havaya kaldırmak yasaktır." },
    { en: "Striking while holding the ropes is not allowed.", alt: "Don't hold ropes.", ph: "Strayking vayl holding dı roops iz not ılaud.", phs: "Doont hoold roops.", tr: "İpleri tutarak vurmak yasaktır." },
    { en: "Do not use the ropes unfairly.", alt: "Don't use ropes.", ph: "Duu not yuuz dı roops anferli.", phs: "Doont yuuz roops.", tr: "İplerden haksız destek alma." },
    { en: "Falling on to an opponent on the floor is not allowed.", alt: "Don't fall on opponent.", ph: "Foolıng on tu en ıpoonınt on dı floor iz not ılaud.", phs: "Doont fool on ıpoonınt.", tr: "Düşen sporcunun üstüne bilerek düşmek yasaktır." },
    { en: "Striking a down opponent is not allowed.", alt: "Don't strike a down athlete.", ph: "Strayking ey daun ıpoonınt iz not ılaud.", phs: "Doont strayk ey daun esliit.", tr: "Yerdeki sporcuya vurmak yasaktır." },
    { en: "Striking while your body touches the floor is not allowed.", alt: "Don't strike from the floor.", ph: "Strayking vayl yor badi taçız dı floor iz not ılaud.", phs: "Doont strayk fram dı floor.", tr: "Ayak dışında bir yerin yerdeyken vuruş yapmak yasaktır." },
    { en: "Intentionally falling to avoid a hit is not allowed. Fight!", alt: "Don't fall. Fight!", ph: "İntenşınıli foolıng tu ıvoyd ey hit iz not ılaud. Fayt!", phs: "Doont fool. Fayt!", tr: "Darbeden kaçmak için kendini yere atma yasaktır. Dövüş!" },
    { en: "Striking the groin is not allowed.", alt: "No groin.", ph: "Strayking dı groyn iz not ılaud.", phs: "Noo groyn.", tr: "Kasık bölgesine vuruş yasaktır." },
    { en: "Striking the cervical spine is not allowed.", alt: "No back of the neck.", ph: "Strayking dı servıkıl spayn iz not ılaud.", phs: "Noo bek of dı nek.", tr: "Boyun arkasına (enseye) vuruş yasaktır." },
    { en: "Do not hold the leg.", alt: "Don't hold the leg.", ph: "Duu not hoold dı leg.", phs: "Doont hoold dı leg.", tr: "Bacak tutmak yasaktır." },
    { en: "Do not hold the arm.", alt: "Don't hold the arm.", ph: "Duu not hoold dı arm.", phs: "Doont hold dı arm.", tr: "Kol tutmak yasaktır." },
    { en: "Do not hold the gloves.", alt: "Don't hold the gloves.", ph: "Duu not hoold dı glavz.", phs: "Doont hoold dı glavz.", tr: "Eldiven tutmak yasaktır." },
    { en: "Pushing forward more than two steps without striking is not allowed.", alt: "Don't push. Fight!", ph: "Puşing forvırd moor den tuu steps vidaut strayking iz not ılaud.", phs: "Doont puş. Fayt.", tr: "Vurmadan 2 adımdan fazla ilerleme yasaktır." },
    { en: "Striking after the YOOT is not allowed.", alt: "No strike after YOOT.", ph: "Strayking aftır dı YUUT iz not ılaud.", phs: "Noo strayk aftır YUUT.", tr: "Yoot komutundan sonra vuruş yapmak yasaktır!" },
    { en: "You must follow my commands immediately.", alt: "Obey my commands. Listen to me!", ph: "Yu mast foloo may kımandz imiidiyıtli.", phs: "Obey may kımandz. Lisın tu mi!", tr: "Komutlarıma uymak zorundasın. Beni iyi dinle!" },
    { en: "Useless or aggressive utterance is not allowed. Calm down.", alt: "Calm down. No talking.", ph: "Yuuslıs or egresiv atırıns iz not ılaud. Kam daun.", phs: "Kam daun. Noo tooking.", tr: "Agresif/gereksiz konuşma yasaktır. Sakin ol." },
    { en: "No knees to the head.", alt: "No knee to head.", ph: "Noo niiz tu dı hed.", phs: "Noo nii tu hed.", tr: "Kafaya diz yasaktır." },
    { en: "No elbows to the head.", alt: "No elbow to head.", ph: "Noo elbooz tu dı hed.", phs: "Noo elboo tu hed.", tr: "Kafaya dirsek yasaktır." },
    { en: "No strikes to the head.", alt: "No strike to head.", ph: "Noo strayks tu dı hed.", phs: "Noo strayk tu hed.", tr: "Kafaya vuruş yasaktır." },
    { en: "No strikes to the face.", alt: "No strike to face.", ph: "Noo strayks tu dı feys.", phs: "Noo strayk tu feys.", tr: "Yüze vuruş yasaktır." },
  ],

  d2_ceza: [
    { en: "Warning for unsportsmanlike behaviour.", alt: "[Colour], Warning, Unsportsmanlike.", ph: "Vorning for ansportsmınlayk biheyvyır.", phs: "[Reng] Vorning, Ansportsmınlayk.", tr: "Sportmenlik dışı davranış — Ceza (Warning)." },
    { en: "Warning for striking a down opponent.", alt: "[Colour], Warning, Striking down athlete.", ph: "Vorning for strayking ey daun ıpoonınt.", phs: "[Reng] Vorning, Strayking daun esliit.", tr: "Yerdeki sporcuya vurma — Ceza (Warning)." },
    { en: "Warning for removing the gum shield.", alt: "[Colour], Warning, Gum shield.", ph: "Vorning for rimuuvıng dı gam şiild.", phs: "[Reng] Vorning, Gam şiild.", tr: "Dişliği bilerek çıkarma — Ceza (Warning)." },
    { en: "Warning for illegal sweep.", alt: "[Colour], Warning, Illegal sweep.", ph: "Vorning for iliigıl sviip.", phs: "[Reng] Vorning, İliigıl sviip.", tr: "Kuralsız süpürme — Ceza (Warning)." },
    { en: "Warning for wrestling.", alt: "[Colour], Warning, Wrestling.", ph: "Vorning for resling.", phs: "[Reng] Vorning, Resling.", tr: "Güreşme/sarılıp dalma — Ceza (Warning)." },
    { en: "Warning for biting.", alt: "[Colour], Warning, Biting.", ph: "Vorning for bayting.", phs: "[Reng] Vorning, Bayting.", tr: "Rakibi ısırma — Ceza (Warning)." },
    { en: "Warning for headbutting.", alt: "[Colour], Warning, Headbutt.", ph: "Vorning for hedbating.", phs: "[Reng] Vorning, Hedbat.", tr: "Rakibe kafa atma — Ceza (Warning)." },
    { en: "Warning for spitting.", alt: "[Colour], Warning, Spitting.", ph: "Vorning for spiting.", phs: "[Reng] Vorning, Spiting.", tr: "Tükürme — Ceza (Warning)." },
    { en: "Warning for knee to the head.", alt: "[Colour], Warning, Knee to head.", ph: "Vorning for nii tu dı hed.", phs: "[Reng] Vorning, Nii tu hed.", tr: "Kafaya diz — Ceza (Warning)." },
    { en: "Warning for elbow to the head.", alt: "[Colour], Warning, Elbow to head.", ph: "Vorning for elboo tu dı hed.", phs: "[Reng] Vorning, Elboo tu hed.", tr: "Kafaya dirsek — Ceza (Warning)." },
    { en: "Warning for strike to the head.", alt: "[Colour], Warning, Strike to head.", ph: "Vorning for strayk tu dı hed.", phs: "[Reng] Vorning, Strayk tu hed.", tr: "Yasak kafaya vuruş — Ceza (Warning)." },
  ],

  d2_karar: [
    { en: "WP — Win on Points", alt: "Winner is Red/Blue.", ph: "Dabıl-yu Pii — Vin on Poynts", phs: "Vinır iz Red / Bluu.", tr: "Puanla Kazanma" },
    { en: "RSC-S — Referee Stops Contest (Safety)", alt: "Winner is Red/Blue.", ph: "Ar Es Sii Es — Referii Stops Kontest (Seyfti)", phs: "Vinır iz Red / Bluu.", tr: "Hakem Kararıyla Maçın Bitmesi — Güvenlik" },
    { en: "RSC-I — Referee Stops Contest (Injury)", alt: "Winner is Red/Blue.", ph: "Ar Es Sii Ay — Referii Stops Kontest (İncıri)", phs: "Vinır iz Red / Bluu.", tr: "Hakem Kararıyla Maçın Bitmesi — Sakatlık" },
    { en: "RSC-H — Referee Stops Contest (Head Strike)", alt: "Winner is Red/Blue.", ph: "Ar Es Sii Eyç — Referii Stops Kontest (Hed Strayk)", phs: "Vinır iz Red / Bluu.", tr: "Hakem Kararıyla Maçın Bitmesi — Kafaya Ağır Darbe" },
    { en: "RSC-B — Referee Stops Contest (Body Strike)", alt: "Winner is Red/Blue.", ph: "Ar Es Sii Bii — Referii Stops Kontest (Badi Strayk)", phs: "Vinır iz Red / Bluu.", tr: "Hakem Kararıyla Maçın Bitmesi — Gövdeye Ağır Darbe" },
    { en: "CCL — Compulsory Count Limit", alt: "Winner is Red/Blue.", ph: "Sii Sii El — Kampalsıri Kaunt Limıt", phs: "Vinır iz Red / Bluu.", tr: "Zorunlu Sayma Limiti" },
    { en: "KO-H — Knockout (Head Strike)", alt: "Winner is Red/Blue.", ph: "Key Oo Eyç — Nokaut (Hed Strayk)", phs: "Vinır iz Red / Bluu.", tr: "Nakavt — Kafaya Darbe" },
    { en: "KO-B — Knockout (Body Strike)", alt: "Winner is Red/Blue.", ph: "Key Oo Bii — Nokaut (Badi Strayk)", phs: "Vinır iz Red / Bluu.", tr: "Nakavt — Gövdeye Darbe" },
    { en: "RET — Retirement", alt: "Winner is Red/Blue.", ph: "Ar İi Tii — Ritayırmınt", phs: "Vinır iz Red / Bluu.", tr: "Çekilme / Köşenin maçı bırakması" },
    { en: "DQ — Disqualification", alt: "Winner is Red/Blue.", ph: "Dii Kyuu — Diskuolıfikeyşın", phs: "Vinır iz Red / Bluu.", tr: "Diskalifiye" },
    { en: "WO — Walk Over", alt: "Winner is Red/Blue.", ph: "Dabıl-yu Oo — Vook Ovır", phs: "Vinır iz Red / Bluu.", tr: "Hükmen Galibiyet" },
    { en: "DRAW — No winner.", alt: "Draw.", ph: "Dıraav — Noo Vinır.", phs: "Dıraav.", tr: "Beraberlik — Kazanan yok" },
    { en: "NC — No Contest", alt: "No contest.", ph: "En Sii — Noo Kontest.", phs: "Noo kontest.", tr: "Geçersiz Maç" },
  ],

  d2_doktor: [
    { en: "Can the athlete continue?", alt: "Can he continue?", ph: "Kan dı esliit kantinyu?", phs: "Kan hi kantinyu?", tr: "Sporcu devam edebilir mi?" },
    { en: "What is the situation?", alt: "What's the situation?", ph: "Vat iz dı siçueyşın?", phs: "Vats dı siçueyşın?", tr: "Durum nedir?" },
    { en: "Please do not enter the ring.", alt: "Don't enter the ring.", ph: "Pliiz duu not entır dı ring.", phs: "Doont entır dı ring.", tr: "Ringe girmeyin." },
    { en: "You may enter the ring.", alt: "Enter the ring.", ph: "Yu mey entır dı ring.", phs: "Entır dı ring.", tr: "Ringe girebilirsiniz." },
  ],

  d2_tayca: [],

  // ── JUDGE ─────────────────────────────────
  d2_yan: [
    { en: "The scorecard is finished.", alt: "No scorecards left.", ph: "Dı skoorkard iz finişt.", phs: "Noo skoorkard left.", tr: "Skor kartı bitti." },
    { en: "I need a pen, please.", alt: "Pen, please.", ph: "Ay niid ey pen, pliiz.", phs: "Pen, pliiz.", tr: "Kaleme ihtiyacım var." },
    { en: "Please step back.", alt: "Step back.", ph: "Pliiz step bek.", phs: "Step bek.", tr: "Lütfen geriye gidiniz." },
  ],

  d2_skor: [
    { en: "I am pressing the button.", alt: "I'm pressing.", ph: "Ay em presıng dı batın.", phs: "Aym presıng.", tr: "Butona basıyorum." },
    { en: "I did not press the button.", alt: "", ph: "Ay did not pres dı batın.", phs: "", tr: "Butona basmadım." },
    { en: "I pressed the wrong button.", alt: "", ph: "Ay prest dı rong batın.", phs: "", tr: "Butona yanlış bastım." },
    { en: "I reset the score by mistake.", alt: "", ph: "Ay riiset dı skoor bay misteyk.", phs: "", tr: "Yanlışlıkla skoru resetledim." },
    { en: "The cable came out.", alt: "Cable unplugged.", ph: "Dı keybıl keym aut.", phs: "Keybıl anplagd.", tr: "Kablo çıktı." },
    { en: "I gave the point to the wrong corner.", alt: "Wrong corner point.", ph: "Ay geyv dı poynt tu dı rong kornır.", phs: "Rong kornır poynt.", tr: "Yanlış köşeye puan verdim." },
    { en: "Everything is okay.", alt: "All good.", ph: "Evriting iz okey.", phs: "Ol gud.", tr: "Her şey yolunda." },
  ],

  // ── TIMEKEEPER ────────────────────────────
  d2_zaman: [
    { en: "The system has stopped.", alt: "System stopped.", ph: "Dı sistım haz stopt.", phs: "Sistım stopt.", tr: "Sistem durdu." },
    { en: "There is no sound.", alt: "No sound.", ph: "Der iz noo saund.", phs: "Noo saund.", tr: "Ses gelmiyor." },
    { en: "I stopped the time.", alt: "Time stopped.", ph: "Ay stopt dı taym.", phs: "Taym stopt.", tr: "Zamanı durdurdum." },
    { en: "I started the time.", alt: "Time started.", ph: "Ay staartıd dı taym.", phs: "Taym staartıd.", tr: "Zamanı başlattım." },
  ],

  // ── ANNOUNCER ─────────────────────────────
  d2_anons: [
    { en: "Next bout, red corner [Name] from [Country], blue corner [Name] from [Country], please get ready.", alt: "Next bout, get ready.", ph: "Nekst baut, red kornır [Neym] fram [Kantri], bluu kornır [Neym] fram [Kantri], pliiz get redi.", phs: "Nekst baut, get redi.", tr: "Bir sonraki maçın sporcuları; kırmızı köşe, mavi köşe hazırlansınlar lütfen." },
    { en: "Ring A, Bout number 2, red corner [Name] from [Country] to the ring area!", alt: "Ring A, Bout 2, Red corner to the ring!", ph: "Ring Ey, Baut nambır tuu, red kornır [Neym] fram [Kantri] tu dı ring erya!", phs: "Ring Ey, Baut tuu, Red kornır tu dı ring!", tr: "A Ringi 2. Maç, Kırmızı köşe sporcusu ring alanına!" },
    { en: "Ring B, Bout number 3, blue corner [Name] from [Country] to the ring area!", alt: "Ring B, Bout 3, Blue corner to the ring!", ph: "Ring Bii, Baut nambır thrii, bluu kornır [Neym] fram [Kantri] tu dı ring erya!", phs: "Ring Bii, Baut thrii, Bluu kornır tu dı ring!", tr: "B Ringi 3. Maç, Mavi köşe sporcusu ring alanına!" },
    { en: "This is the final call!", alt: "Final call!", ph: "Dis iz dı faynıl kool!", phs: "Faynıl kool!", tr: "Son çağrı!" },
    { en: "The winner is the red corner.", alt: "Winner, red corner.", ph: "Dı vinır iz dı red kornır.", phs: "Vinır, red kornır.", tr: "Kazanan kırmızı köşe." },
    { en: "The winner is the blue corner.", alt: "Winner, blue corner.", ph: "Dı vinır iz dı bluu kornır.", phs: "Vinır, bluu kornır.", tr: "Kazanan mavi köşe." },
    { en: "The bouts are paused for one hour.", alt: "One hour break.", ph: "Dı bauts ar paazd for van auır.", phs: "Van auır breyk.", tr: "Maçlara bir saat ara verilmiştir." },
    { en: "Seconds out!", alt: "Seconds out!", ph: "Sekındz aut!", phs: "Sekındz aut!", tr: "Yardımcılar dışarı!" },
  ],
};

window.DAY2_QUIZ = [
  { sit: "Bir sporcunun eldivenleri hem onaysız hem de yıpranmış görünüyor.", q: "Ne söylersin?", opts: ["These gloves are not acceptable. Please change them.", "The gloves are loose. Please tape them.", "Only IFMA approved gloves are allowed.", "Can I see your gloves?"], c: 0, ex: "✓ 'These gloves are not acceptable. Please change them.'" },
  { sit: "Sporcu kaskını takmadan ringe çıkmaya hazırlanıyor.", q: "Ne söylersin?", opts: ["Put on your headguard.", "Remove your headguard.", "Can I see your headguard?", "Fix the headguard."], c: 0, ex: "✓ 'Put on your headguard.' — kask takma komutu." },
  { sit: "Çok fazla vazelin sürülmüş, kurallara aykırı.", q: "Ne söylersin?", opts: ["Too much Vaseline. Please wipe it off.", "The gloves are loose. Please tape them.", "Please remove your jewelry.", "Show me your bandage."], c: 0, ex: "✓ 'Too much Vaseline. Please wipe it off.'" },
  { sit: "Köşe görevlisi ceketiyle görev yerine geliyor.", q: "Ne söylersin?", opts: ["Please remove your jacket.", "Only sports shoes are allowed.", "Do not remove the gloves.", "Please take the water bottle."], c: 0, ex: "✓ 'Please remove your jacket.'" },
  { sit: "Köşe görevlisi havluyu almayı unuttu.", q: "Ne söylersin?", opts: ["Please remove the towel.", "Please lean over the ropes.", "Do not remove the gloves.", "Fix the headguard."], c: 0, ex: "✓ 'Please remove the towel.'" },
  { sit: "Aynı raundda 2 kere saydın, Başhakeme bildiriyorsun.", q: "Ne söylersin?", opts: ["I counted twice in the same round.", "I counted twice in total.", "I geyv two cautions.", "I counted three times in total."], c: 0, ex: "✓ 'I counted twice in the same round.'" },
  { sit: "Sporcunun kasık koruyucusu yok.", q: "Ne bildirirsin?", opts: ["The athlete has no groin guard.", "The athlete has no chest protector.", "The athlete has no bandage.", "The headguard is not approved."], c: 0, ex: "✓ 'The athlete has no groin guard.'" },
  { sit: "Hangi ringde görev yapacağını öğrenmek istiyorsun.", q: "Ne sorarsın?", opts: ["Which ring is it?", "Which bout number is it?", "What is my duty?", "Which weight division is it?"], c: 0, ex: "✓ 'Which ring is it?'" },
  { sit: "Skor kartın bitti.", q: "Ne söylersin?", opts: ["The scorecard is finished.", "I need a pen, please.", "Please step back.", "I pressed the wrong button."], c: 0, ex: "✓ 'The scorecard is finished.'" },
  { sit: "Yanlış köşeye puan verdiğini fark ettin.", q: "Ne söylersin?", opts: ["I geyv the point to the wrong corner.", "I pressed the wrong button.", "I reset the score by mistake.", "I did not press the button."], c: 0, ex: "✓ 'I geyv the point to the wrong corner.'" },
  { sit: "Zaman hakemi olarak sistem durdu.", q: "Ne söylersin?", opts: ["The system has stopped.", "There is no sound.", "I stopped the time.", "I started the time."], c: 0, ex: "✓ 'The system has stopped.'" },
  { sit: "Sporcu ringe gelmedi, son kez çağırıyorsun.", q: "Ne söylersin?", opts: ["This is the final call!", "Seconds out!", "The bouts are paused for one hour.", "Next bout, get ready."], c: 0, ex: "✓ 'This is the final call!'" },
  { sit: "Maç başlamadan önce sporcuları ortaya çağırıyorsun.", q: "Ne söylersin?", opts: ["Red, Blue, come to the center. Shake hands. Good luck. To your corners.", "Put on your headguard. Listen to my commands.", "This is your first caution.", "Will you continue?"], c: 0, ex: "✓ 'Red, Blue, come to the center. Shake hands. Good luck. To your corners.'" },
  { sit: "Sporcu son kez kurala aykırı hareket yaptı.", q: "Ne söylersin?", opts: ["This is your last caution.", "This is your second caution.", "This is your first caution.", "Warning for unsportsmanlike behaviour."], c: 0, ex: "✓ 'This is your last caution.'" },
  { sit: "Sporcu kasıtlı olarak dişliğini çıkarttı, ceza veriyorsun.", q: "Jüriye ne bildirirsin?", opts: ["Warning for removing the gum shield.", "Warning for spitting.", "Warning for wrestling.", "Warning for biting."], c: 0, ex: "✓ 'Warning for removing the gum shield.'" },
  { sit: "Yoot komutundan sonra sporcu vuruşuna devam etti.", q: "Ne söylersin?", opts: ["Striking after the YOOT is not allowed.", "You must follow my commands immediately.", "No shaking hands during the fight.", "Intentionally falling to avoid a hit is not allowed. Fight!"], c: 0, ex: "✓ 'Striking after the YOOT is not allowed.'" },
  { sit: "Maç puanla sonuçlandı, kırmızı köşe kazandı.", q: "Karar kısaltması hangisi?", opts: ["WP — Winner is Red corner.", "RSC-S — Winner is Red corner.", "KO-H — Winner is Red corner.", "DQ — Winner is Red corner."], c: 0, ex: "✓ WP — Win on Points. Puanla kazanma." },
  { sit: "Sporcu başına ağır darbe aldı, hakem maçı durdurdu.", q: "Karar kısaltması hangisi?", opts: ["RSC-H", "RSC-B", "RSC-I", "KO-B"], c: 0, ex: "✓ RSC-H — Referee Stops Contest, Head Strike." },
  { sit: "Maç berabere sonuçlandı.", q: "Karar hangisi?", opts: ["DRAW", "WP", "NC", "WO"], c: 0, ex: "✓ DRAW — Beraberlik, kazanan yok." },
  { sit: "Doktor ringe girmek istiyor ama henüz izin verilmedi.", q: "Ne söylersin?", opts: ["Please do not enter the ring.", "You may enter the ring.", "Can the athlete continue?", "What is the situation?"], c: 0, ex: "✓ 'Please do not enter the ring.'" },
  { sit: "Ring zemini kayıyor.", q: "Ne söylersin?", opts: ["The canvas is too wet and slippery.", "The canvas needs to be cleaned.", "The ropes are loose.", "The canvas needs to be fixed."], c: 0, ex: "✓ 'The canvas is too wet and slippery.'" },
  { sit: "Başın dönüyor.", q: "Ne söylersin?", opts: ["I feel dizzy.", "I don't feel well. May I rest?", "I need to see a doctor.", "My blood pressure is high."], c: 0, ex: "✓ 'I feel dizzy.'" },
];

window.DAY2_SECTIONS = [
  { id: "d2_juri_rap", label: "Raporlama (Reporting)" },
  { id: "d2_juri_diy", label: "Genel İletişim (Communication)" },
  { id: "d2_juri_gov", label: "Görevlendirme (Assignment)" },
  { id: "d2_hakem",    label: "Hakem Sağlık (Referee Health)" },
  { id: "d2_ring",     label: "Ring" },
  { id: "d2_ekipman",  label: "Ekipman Kontrolü (Equipment Check)" },
  { id: "d2_kose",     label: "Köşe Görevlisi (Second)" },
  { id: "d2_orta",     label: "Komutlar (Referee Commands)" },
  { id: "d2_uyari",    label: "Uyarılar (Cautions)" },
  { id: "d2_ceza",     label: "Cezalar (Warnings)" },
  { id: "d2_karar",    label: "Kararlar (Decisions)" },
  { id: "d2_doktor",   label: "Doktor (Doctor)" },
  { id: "d2_tayca",    label: "Tayca Sayma (Thai Count)" },
  { id: "d2_yan",      label: "Yan Hakem (Judge)" },
  { id: "d2_skor",     label: "Skorlama (Scoring System)" },
  { id: "d2_zaman",    label: "Zaman Hakemi (Timekeeper)" },
  { id: "d2_anons",    label: "Anons Hakemi (Announcer)" },
];

// ── JURY SENARYO PRATİĞİ ───────────────────────────────────────────
window.QUIZ_JURY = [
  { en: "During a round, you geyv a knock-down count to the same athlete two times. If requested, you report the count status to the Jury.", tr: "Bir raund içinde aynı sporcuya iki kez nakavt sayımı (knock-down count) yaptın. Talep edildiği takdirde; sayma durumunu jüriye rapor ediyorsun.", q: "Ne söylersin?", opts: ["I counted twice in the same round.", "I counted twice in total.", "I counted once in the same round.", "I geyv two cautions."], c: 0, ex: "✓ 'I counted twice in the same round.'" },
  { en: "An athlete receives their third count within a single round. If requested, you report the count status to the jury.", tr: "Bir sporcu tek bir raund içinde üçüncü kez sayma aldı. Talep edildiği takdirde; sayma durumunu jüriye rapor ediyorsun.", q: "Ne söylersin?", opts: ["I counted three times in the same round.", "I counted three times in total.", "Three counts total.", "I geyv three cautions."], c: 0, ex: "✓ 'I counted three times in the same round.'" },
  { en: "You issued two cautions to the red corner during the bout. If requested, you report the count status to the Jury.", tr: "Maç esnasında kırmızı köşeye iki resmi sözlü uyarı verdin. Talep edildiği takdirde; sayma durumunu jüriye rapor ediyorsun.", q: "Ne söylersin?", opts: ["I geyv two cautions.", "Two counts total.", "I geyv three cautions.", "Two counts, same round."], c: 0, ex: "✓ 'I geyv two cautions.'" },
  { en: "During the glove check at the ring entrance, you notice the athlete has no hand wraps under their gloves. Report this violation to the Jury.", tr: "Ring girişindeki eldiven kontrolünde sporcunun eldivenlerinin altında bandaj olmadığını fark ediyorsun. Bu ihlali jüriye rapor ediyorsun.", q: "Ne bildirirsin?", opts: ["The athlete has no bandage.", "Show me your bandage.", "This bandage is not acceptable. Please change it.", "No groin guard."], c: 0, ex: "✓ 'The athlete has no bandage.'" },
  { en: "You need to ask the jury if the second is permitted to replace a faulty headguard.", tr: "Köşe Görevlisinin kusurlu bir kaskı değiştirmesine izin verilip verilmediğini jüriye sorman gerekiyor.", q: "Ne sorarsın?", opts: ["Can they change the headguard?", "Can I see your headguard?", "Show me your bandage.", "Headguard not approved. Must be changed."], c: 0, ex: "✓ 'Can they change the headguard?'" },
  { en: "You need a tape to secure an athlete's equipment. Ask the Jury for assistance.", tr: "Bir sporcunun ekipmanını sabitlemek için banda ihtiyacın var. Jüriden yardım istiyorsun.", q: "Ne sorarsın?", opts: ["Can you give me some tape?", "Can you give me a hair net?", "The gloves are loose. Please tape them.", "Tape the gloves."], c: 0, ex: "✓ 'Can you give me some tape?'" },
  { en: "A female athlete comes to the ring wearing a black hijab. Report this immediately to the Jury.", tr: "Bir kadın sporcu ringe siyah hicapla geliyor. Bunu derhal jüriye rapor ediyorsun.", q: "Ne bildirirsin?", opts: ["The athlete's hijab is not approved.", "The hijab/body suit must be white.", "Can you give me a hair net?", "This shirt is not approved. Please change it."], c: 0, ex: "✓ 'The athlete's hijab is not approved.'" },
  { en: "During the pre-fight, you learned the athlete is missing their groin guard. Report this immediately to the Jury.", tr: "Maç öncesi sporcunun kasık koruyucusunun olmadığını öğreniyorsun. Bunu derhal jüriye rapor ediyorsun.", q: "Ne bildirirsin?", opts: ["The athlete has no groin guard.", "Do you have a groin guard.", "The athlete's hijab is not approved.", "The athlete has no chest protector."], c: 0, ex: "✓ 'The athlete has no groin guard.'" },
  { en: "You inspect the athlete's body protection and see it is not IFMA approved. Inform the Jury that a replacement is mandatory.", tr: "Sporcunun gövde koruyucusunu inceliyorsun ve IFMA onaylı olmadığını görüyorsun. Değiştirilmesinin zorunlu olduğunu jüriye bildiriyorsun.", q: "Ne söylersin?", opts: ["The chest protector is not approved. It must be changed.", "Do you have a chest protector?", "The athlete has no chest protector.", "Chest protector not approved. Must be changed."], c: 0, ex: "✓ 'The chest protector is not approved. It must be changed.'" },
  { en: "You need to leave the field of play briefly to use the toilet. Ask the Protocol Jury for permission.", tr: "Tuvaleti kullanmak için müsabaka alanından kısa süreliğine ayrılmanız gerekiyor. Protokol Jürisinden izin istiyorsunuz.", q: "Ne sorarsın?", opts: ["May I go to the restroom?", "I need to make a phone call. May I?", "Can you help me, please?", "Which number should I go to?"], c: 0, ex: "✓ 'May I go to the restroom?'" },
  { en: "You must contact someone by phone. Ask the Protocol Jury for permission.", tr: "Telefonla birine ulaşmanız gerekiyor. Protokol Jürisinden izin istiyorsunuz.", q: "Ne sorarsın?", opts: ["I need to make a phone call. May I?", "Thank you for your understanding.", "Can you help me, please?", "May I go to the restroom?"], c: 0, ex: "✓ 'I need to make a phone call. May I?'" },
  { en: "The Jury points out a small positioning mistake you made in the last round. Acknowledge the feedback and state that you will be careful.", tr: "Jüri son raundda yaptığınız küçük bir pozisyon hatasına dikkat çekiyor. Geri bildirimi kabul edip dikkat edeceğinizi belirtiyorsunuz.", q: "Ne söylersin?", opts: ["Thank you for your feedback. I will be careful.", "Thank you for your understanding.", "Can you help me, please?", "I need to make a phone call. May I?"], c: 0, ex: "✓ 'Thank you for your feedback. I will be careful.'" },
  { en: "You accidentally miscalculated a score or count, and the Jury corrects you. Apologize for your fault and assure them you'll pay attention.", tr: "Yanlışlıkla bir skoru veya saymayı hatalı hesapladınız ve Jury sizi düzeltti. Hatanız için özür dileyip dikkat edeceğinizi garanti ediyorsunuz.", q: "Ne söylersin?", opts: ["I am sorry for my mistake. I will be careful.", "I can help you.", "What is my duty?", "Thank you for your understanding."], c: 0, ex: "✓ 'I am sorry for my mistake. I will be careful.'" },
  { en: "You see another referee carrying heavy equipment or struggling with a task at the table. Offer your assistance.", tr: "Başka bir hakemin masada ağır ekipman taşıdığını veya bir görevde zorlandığını görüyorsunuz. Yardım teklif ediyorsunuz.", q: "Ne söylersin?", opts: ["I can help you.", "Can you help me, please?", "What is my duty?", "Which weight division is it?"], c: 0, ex: "✓ 'I can help you.'" },
  { en: "You are told that you have an assignment, but you don't remember the specific role (e.g., judge or referee). Ask for clarification.", tr: "Size bir assignment (görev) verildiği söylendi ancak tam olarak rolünüzü (yan hakem mi, orta hakem mi) hatırlamıyorsunuz. Netleştirmek için soruyorsunuz.", q: "Ne sorarsın?", opts: ["What is my duty?", "Which category is it?", "Which number should I go to?", "Which bout number is it?"], c: 0, ex: "✓ 'What is my duty?'" },
  { en: "You are assigned as a Judge, but you don’t remember which specific judge chair (1, 2, 3, 4, or 5) you need to sit on. Ask.", tr: "Yan hakem olarak görevlendirildiniz ancak tam olarak kaç numaralı hakem sandalyesine (1, 2, 3, 4 veya 5) oturacağınızı hatırlamıyorsunuz. Soruyorsunuz.", q: "Ne sorarsın?", opts: ["Which number should I go to?", "Which bout number is it?", "My duty?", "Which ring is it?"], c: 0, ex: "✓ 'Which number should I go to?'" },
  { en: "You want to look at the official assignment list to see the referee duties. Ask for permission.", tr: "Hakem görevlendirmelerini görmek için resmi görevlendirme listesine bakmak istiyorsunuz. İzin istiyorsunuz.", q: "Ne sorarsın?", opts: ["May I check the duty list?", "What is my duty?", "Which number should I go to?", "Which category is it?"], c: 0, ex: "✓ 'May I check the duty list?'" },
  { en: "To prepare for your assignment, you want to know which category the upcoming match is in.", tr: "Görevine hazırlanmak için yaklaşan maçın hangi kategori olduğunu öğrenmek istiyorsun.", q: "Ne sorarsın?", opts: ["Which category is it?", "Which bout number is it?", "Which division?", "Which weight division is it?"], c: 0, ex: "✓ 'Which category is it?'" },
  { en: "You need to check the match order to know exactly when you need to be ready at the ring side. Ask for the specific bout number.", tr: "Tam olarak ne zaman ring kenarında hazır olmanız gerektiğini bilmek için maç sırasını kontrol etmeniz gerekiyor. Maç numarasını soruyorsunuz.", q: "Ne sorarsın?", opts: ["Which bout number is it?", "Which ring is it?", "Which weight division is it?", "May I check the duty list?"], c: 0, ex: "✓ 'Which bout number is it?'" },
  { en: "An athlete receives a hard punch, and their nose starts bleeding significantly. While the doctor is checking, report the specific situation to the approaching jury official.", tr: "Bir sporcu sert bir yumruk alıyor ve burnu ciddi şekilde kanamaya başlıyor. Doktor kontrol ederken, yanınıza gelen jüri görevlisine bu durumu rapor ediyorsunuz.", q: "Ne bildirirsin?", opts: ["The athlete's nose is bleeding.", "The athlete took a heavy strike to the head.", "The athlete is down.", "The athlete vomited."], c: 0, ex: "✓ 'The athlete's nose is bleeding.'" },
  { en: "An athlete gets caught with a massive high kick or spinning elbow to the head and knocked down. The doctor enters the ring; report the cause of injury to the jury.", tr: "Bir sporcu kafasına çok ağır bir yüksek tekme veya döner dirsek alıyor ve nakavt oluyor. Doktor ringe giriyor; jüriye sakatlığın nedenini rapor ediyorsunuz.", q: "Ne bildirirsin?", opts: ["The athlete took a heavy strike to the head.", "The athlete vomited.", "The athlete took a heavy strike to the body.", "The athlete fainted."], c: 0, ex: "✓ 'Heavy head strike.'" },
  { en: "After an accidental low blow, the fighter drops to the canvas in severe pain. While waiting for the doctor, inform the technical officials about the exact location of the strike.", tr: "Yanlışlıkla atılan alçak vuruş sonrasında dövüşçü büyük bir acıyla yere düşüyor. Doktoru beklerken teknik görevlilere darbenin tam yerini bildiriyorsunuz.", q: "Ne bildirirsin?", opts: ["The athlete took a heavy strike to the groin.", "The athlete fainted.", "The athlete took a heavy strike to the body/ Heavy head strike.", "No strike to groin."], c: 0, ex: "✓ 'Heavy groin strike.'" },
  { en: "A fighter is hit with a hard knee strike to the ribs and cannot stand up straight (KO). Report the condition to the Jury.", tr: "Bir dövüşçü kaburgalarına sert bir diz vuruşu alıyor ve dik duramıyor (KO). Jüriye durumu rapor ediyorsunuz.", q: "Ne bildirirsin?", opts: ["The athlete took a heavy strike to the body.", "The athlete fainted.", "The chest protector is not approved. It must be changed.", "The athlete took a heavy strike to the head."], c: 0, ex: "✓ 'Heavy body strike.'" },
  { en: "During the intense clinch or after a hard body shot, the athlete feels sick and throws up on the canvas. Turn to the Jury and state what happened.", tr: "Yoğun bir clinch esnasında veya sert bir gövde darbesinden sonra sporcu fenalaşıyor ve ring zeminine kusuyor. Jüriye dönüp ne olduğunu bildiriyorsunuz.", q: "Ne bildirirsin?", opts: ["The athlete vomited.", "Heavy head strike.", "The athlete fainted.", "Fainted."], c: 0, ex: "✓ 'The athlete vomited.'" },
  { en: "An athlete takes a heavy knockout blow and loses consciousness completely on the floor. While the medical team is responding, report the status to the Jury.", tr: "Bir sporcu ağır bir nakavt darbesi alıyor ve yerde bilincini tamamen kaybediyor (bayılıyor). Sağlık ekibi müdahale ederken Jüriye durumu rapor ediyorsunuz.", q: "Ne bildirirsin?", opts: ["The athlete fainted.", "Nose bleeding.", "The athlete vomited.", "Heavy head strike."], c: 0, ex: "✓ 'The athlete fainted.'" },
  { en: "You start feeling unwell during a long session and need to step away from your duty to rest. Inform the Jury.", tr: "Uzun bir seans sırasında kendinizi kötü hissetmeye başladınız ve dinlenmek için görevinizden kısa süre ayrılmanız gerekiyor. Jüriye durumu bildiriyorsunuz.", q: "Ne söylersin?", opts: ["I don't feel well. May I rest?", "I lost my bow tie.", "Can you help me?", "I need to change."], c: 0, ex: "✓ 'I don't feel well. May I rest?'" },
  { en: "You experience a sudden, severe medical issue at the ring side and require professional medical assistance. State your need clearly.", tr: "Ring kenarında ani ve ciddi bir sağlık sorunu yaşadınız ve profesyonel tıbbi yardıma ihtiyacınız var. İhtiyacınızı net bir şekilde belirtiyorsunuz.", q: "Ne söylersin?", opts: ["I need to see a doctor.", "I have a migraine.", "My blood pressure is low.", "My leg hurts."], c: 0, ex: "✓ 'I need to see a doctor.'" },
  { en: "Your head spin, and you feel unstable on your feet. Report this specific sensation.", tr: "Başınız dönüyor ve ayakta durmakta zorlanıyorsunuz. Bu özel durumu rapor ediyorsunuz.", q: "Ne söylersin?", opts: ["I feel dizzy.", "I feel nauseous.", "My leg hurts.", "I have a migraine."], c: 0, ex: "✓ 'I feel dizzy.'" },
  { en: "After a close exchange where you had to split the athletes, you feel a sharp pain in your upper extremity and can’t continue to your duty. Inform the Jury.", tr: "Sporcuları ayırırken üst uzvunuzda (kolunuzda) keskin bir ağrı hissettiniz ve göreve devam edemiyorsunuz. Jüriye bilgi veriyorsunuz.", q: "Ne söylersin?", opts: ["My arm hurts.", "My leg hurts.", "Arm hurts.", "My hand hurts."], c: 0, ex: "✓ 'My arm hurts.'" },
  { en: "You start feeling dynamic stomach discomfort and feel like you might throw up. Inform the Jury immediately.", tr: "Dinamic bir mide rahatsızlığı hissediyorsunuz ve kusacak gibi oluyorsunuz. Gözlemciye derhal bilgi veriyorsunuz.", q: "Ne söylersin?", opts: ["I feel nauseous.", "Arm hurts.", "I feel dizzy.", "The athlete vomited."], c: 0, ex: "✓ 'I feel nauseous.'" },
  { en: "Your lower limb or foot is causing you severe pain. Report it.", tr: "Ayağınız size ciddi acı veriyor. Bunu rapor ediyorsunuz.", q: "Ne söylersin?", opts: ["My foot hurts.", "My hand hurts.", "I feel dizzy.", "My leg hurts."], c: 0, ex: "✓ 'My foot hurts.'" },
  { en: "You are feeling weak, shaky, and sweating. Report your glucose drop to the table.", tr: "Kendinizi halsiz, titrer vaziyette hissediyorsunuz. Şekerinizin düştüğünü masaya bildiriyorsunuz.", q: "Ne söylersin?", opts: ["My blood sugar is low.", "My foot hurts.", "My blood pressure is low.", "I feel dizzy."], c: 0, ex: "✓ 'My blood sugar is low.'" },
  { en: "You notice your blood pressure is spiking, causing a pulsing feeling in your head. Inform the Jury about your hypertension.", tr: "Tansiyonunuzun yükseldiğini ve başınızda zonklama yarattığını fark ettiniz. Jüriye yüksek tansiyon durumunuzu bildiriyorsunuz.", q: "Ne söylersin?", opts: ["My blood pressure is high.", "I feel dizzy.", "My blood pressure is low.", "My blood sugar is low."], c: 0, ex: "✓ 'My blood pressure is high.'" },
  { en: "You realize your bow tie came off and is missing. Ask a colleague or Jury for a spare.", tr: "Ringe çağrılmadan hemen önce papyonunuzun kaybolduğunu fark ettiniz. Bir meslektaşınızdan veya Jüriden yedek istiyorsunuz.", q: "Ne söylersin?", opts: ["I lost my bow tie. Do you have any extra one?", "I lost my Mongkon.", "Headguard not approved. Must be changed.", "Do you have gloves?"], c: 0, ex: "✓ 'I lost my bow tie. Do you have any extra one?'" },
  { en: "You notice that the canvas fabric has unfastened from the corner or has dangerous folds that could trip the athletes. Inform the Jury.", tr: "Ring zemin kaplamasının köşeden çözüldüğünü veya sporcuların takılmasına neden olabilecek tehlikeli katlanmalar oluşturduğunu fark ediyorsunuz. Jüriye bildiriyorsunuz.", q: "Ne bildirirsin?", opts: ["The canvas needs to be fixed.", "Slippery canvas.", "The canvas is too wet and slippery.", "The canvas needs to be cleaned."], c: 0, ex: "✓ 'The canvas needs to be fixed.'" },
  { en: "During a clinch, the athletes lean against the ring boundaries and the lines sag heavily, which is dangerous. Inform the Jury.", tr: "Clinch esnasında sporcular iplere yaslanıyor ve ipler tehlikeli şekilde sarkıyor. Jüriye bildiriyorsunuz.", q: "Ne bildirirsin?", opts: ["The ropes are loose.", "Canvas is dirty.", "The ropes need to be cleaned.", "Ropes are dirty."], c: 0, ex: "✓ 'The ropes are loose.'" },
  { en: "There is dry dirt, or small debris on the ring floor that needs to be swept before the next bout. Request maintenance.", tr: "Bir sonraki maçtan önce ring zemininde süpürülmesi gereken kuru kir veya küçük kalıntılar var. Görevlilerden temizlik talep ediyorsunuz.", q: "Ne talep edersin?", opts: ["The canvas needs to be cleaned.", "Ropes are dirty.", "The canvas is too wet and slippery.", "The canvas needs to be fixed."], c: 0, ex: "✓ 'The canvas needs to be cleaned.'" },
  { en: "An athlete's nosebleed has smeared all over the ring ropes. Request maintenance.", tr: "Bir sporcunun burun kanaması ring iplerinin her yerine bulaşmış. Görevlilerden temizlik talep ediyorsunuz.", q: "Ne talep edersin?", opts: ["The ropes need to be cleaned.", "Ropes are dirty.", "The canvas needs to be fixed.", "The ropes are loose."], c: 0, ex: "✓ 'The ropes need to be cleaned.'" },
  { en: "The seconds poured too much water during the break, and now there is a large puddle on the floor causing athletes to lose traction. Request maintenance.", tr: "Yardımcılar mola esnasında çok fazla su döktü ve zeminde büyük su birikintisi var, sporcular kayıyor. Görevlilerden temizlik talep ediyorsunuz.", q: "Ne bildirirsin?", opts: ["The canvas is too wet and slippery.", "Canvas is dirty.", "The ropes are loose.", "The canvas needs to be fixed."], c: 0, ex: "✓ 'The canvas is too wet and slippery.'" },
];

// ── EQUIPMENT SEKMESİ ──────────────────────────────────────────────
window.QUIZ_EQUIPMENT = [
  { en: "An athlete comes with non-approved gloves. Inform them about the IFMA rule.", tr: "Bir sporcu onaylı olmayan eldivenlerle geliyor. Ona IFMA kuralını bildiriyorsun.", q: "Ne söylersin?", opts: ["Only IFMA approved gloves are allowed.", "Ankle protection is not allowed.", "The gloves must be 10 oz.", "Can I see your gloves?"], c: 0, ex: "✓ 'Only IFMA approved gloves are allowed.'" },
  { en: "You inspect the athlete's shin guards and find them damaged/unsuitable. Tell them to change them.", tr: "Sporcunun kaval koruyucularını inceliyorsun ve uygun olmadığını görüyorsun. Değiştirmesini söylüyorsun.", q: "Ne söylersin?", opts: ["These shin guards are not acceptable. Please change them.", "The shin guards are loose. Please tape them.", "Can I see your gloves?", "Ankle protection is not allowed."], c: 0, ex: "✓ 'These shin guards are not acceptable. Please change them.'" },
  { en: "You notice the athlete's gloves are spinning and not secure. Tell them what to do.", tr: "Sporcunun eldivenlerinin gevşek olduğunu ve döndüğünü fark ediyorsun. Ne yapması gerektiğini söylüyorsun.", q: "Ne söylersin?", opts: ["The gloves are loose. Please tape them.", "Can I see your gloves?", "The gloves must be 10 oz.", "Only IFMA approved gloves are allowed."], c: 0, ex: "✓ 'The gloves are loose. Please tape them.'" },
  { en: "The athlete's t-shirt is hanging outside their shorts. Tell them to fix it.", tr: "Sporcunun tişörtü şortunun dışına sarkıyor. Düzeltmesini söylüyorsun.", q: "Ne söylersin?", opts: ["Please tuck your shirt into your shorts.", "This shirt is not approved. Please change it.", "Please use a hair net.", "Too much Vaseline. Please wipe it off."], c: 0, ex: "✓ 'Please tuck your shirt into your shorts.'" },
  { en: "Instruct the athletes before starting the bout, after the hand shake.", tr: "Maç başlamadan önce ve selamlaşmadan sonra sporculara talimat veriyorsun.", q: "Ne söylersin?", opts: ["Put on your headguard.", "Put on your Mongkon.", "Show me your bandage.", "Can I see your headguard?"], c: 0, ex: "✓ 'Put on your headguard.'" },
  { en: "You need to check the wrapping on the athlete's hands before the gloves go on. Ask them.", tr: "Eldivenler takılmadan önce sporcunun ellerindeki bandajı kontrol etmen gerekiyor.", q: "Ne söylersin?", opts: ["Show me your bandage.", "This bandage is not acceptable. Please change it.", "Can I see your gloves?", "Do you have a groin guard?"], c: 0, ex: "✓ 'Show me your bandage.'" },
  { en: "You notice the athlete has ankle sleeves on under their shin guards, which is forbidden in this division. Inform them.", tr: "Sporcunun kaval koruyucusunun altına ayak bilek koruyucusu (çorap) taktığını fark ediyorsun ki bu kategoride yasak. Bildiriyorsun.", q: "Ne söylersin?", opts: ["Ankle protection is not allowed.", "These shin guards are not acceptable. Please change them.", "The shin guards are loose. Please tape them.", "Your toenails are too long. Please trim them."], c: 0, ex: "✓ 'Ankle protection is not allowed.'" },
  { en: "The athlete has long hair that is coming out of the headguard. Tell them the requirement.", tr: "Sporcunun uzun saçları kaskın dışına taşıyor. Yapması gerekeni söylüyorsun.", q: "Ne söylersin?", opts: ["Please use a hair net.", "Please tuck your shirt into your shorts.", "Put on your headguard.", "The hijab/body suit must be white."], c: 0, ex: "✓ 'Please use a hair net.'" },
  { en: "The coach applied too much grease on the athlete's face. Tell them to clean it.", tr: "Antrenör sporcunun yüzüne çok fazla vazelin sürmüş. Silmelerini söylüyorsun.", q: "Ne söylersin?", opts: ["Too much Vaseline. Please wipe it off.", "Put in your gum shield.", "This chest protector is not acceptable. Please change it.", "Your toenails are too long. Please trim them."], c: 0, ex: "✓ 'Too much Vaseline. Please wipe it off.'" },
  { en: "The athlete comes with a red or pink gum shield, which is forbidden. Tell them to change it.", tr: "Sporcu kırmızı veya pembe renk bir dişlikle geliyor ki bu yasaktır. Değiştirmesini söylüyorsun.", q: "Ne söylersin?", opts: ["This gum shield is not acceptable. Please change it.", "Can I see your gum shield?", "Put in your gum shield.", "Too much Vaseline. Please wipe it off."], c: 0, ex: "✓ 'This gum shield is not acceptable. Please change it.'" },
  { en: "You notice the athlete has a metal or plastic hair clip in their hair. Tell them to remove it.", tr: "Sporcunun saç tokası taktığını fark ediyorsun. Çıkarmasını söylüyorsun.", q: "Ne söylersin?", opts: ["Please remove your hair clip. It is not allowed.", "Please use a hair net.", "Please remove your jewelry. It is not allowed.", "Remove your headguard."], c: 0, ex: "✓ 'Please remove your hair clip. It is not allowed.'" },
  { en: "The athlete put on their headguard and came to the center, but forgot their gum shield. Instruct them.", tr: "Sporcu kaskını takıp ortaya geliyor ama dişliğini takmayı unutmuş. Talimat veriyorsun.", q: "Ne söylersin?", opts: ["Put in your gum shield.", "Can I see your gum shield?", "Put on your headguard.", "Put on your Mongkon."], c: 0, ex: "✓ 'Put in your gum shield.'" },
  { en: "During the equipment check, you need to ask the athlete if they are wearing a groin guard.", tr: "Ekipman kontrolünde sporcuya kasık koruyucusu olup olmadığını soruyorsun.", q: "Ne söylersin?", opts: ["Do you have a groin guard?", "Do you have a chest protector?", "Ankle protection is not allowed.", "Show me your bandage."], c: 0, ex: "✓ 'Do you have a groin guard?'" },
  { en: "During the equipment check, you need to ask a female athlete if she have a chest protector.", tr: "Ekipman kontrolünde kadın sporcuya göğüs koruyucusu olup olmadığını soruyorsun.", q: "Ne söylersin?", opts: ["Do you have a chest protector?", "This chest protector is not acceptable. Please change it.", "Do you have a groin guard?", "This shirt is not approved. Please change it."], c: 0, ex: "✓ 'Do you have a chest protector?'" },
  { en: "The athlete comes to the ring wearing a black hijab/body suit. Tell them it must be white.", tr: "Sporcu siyah renkte bir hicap/vücut örtüsüyle gelmiş. Uygun olmadığını, beyaz giymesi gerektiğini söylüyorsun.", q: "Ne söylersin?", opts: ["The hijab/body suit must be white.", "This shirt is not approved. Please change it.", "Only IFMA approved gloves are allowed.", "These shorts are not approved. Please change them."], c: 0, ex: "✓ 'The hijab/body suit must be white.'" },
  { en: "You check the athlete's feet and notice their toenails are too long. Tell them to trim them.", tr: "Sporcunun ayaklarını kontrol ediyorsun ve ayak tırnaklarının çok uzun olduğunu fark ediyorsun. Kesmelerini söylüyorsun.", q: "Ne söylersin?", opts: ["Your toenails are too long. Please trim them.", "Ankle protection is not allowed.", "Too much Vaseline. Please wipe it off.", "The shin guards are loose. Please tape them."], c: 0, ex: "✓ 'Your toenails are too long. Please trim them.'" },
  { en: "You notice a second wearing sandals or slippers in the corner. Tell them the rule.", tr: "Köşedeki yardımcı antrenörün sandalet veya terlik giydiğini fark ediyorsun. Ona kuralı bildiriyorsun.", q: "Ne söylersin?", opts: ["Only sports shoes are allowed.", "Please remove your jacket.", "Good luck.", "Please lean over the ropes."], c: 0, ex: "✓ 'Only sports shoes are allowed.'" },
  { en: "A second is wearing a heavy jacket or non-sports clothing. Tell them to take it off.", tr: "Köşe görevlisi ağır bir ceket veya spor dışı bir kıyafet giyiyor. Çıkarmasını söylüyorsun.", q: "Ne söylersin?", opts: ["Please remove your jacket.", "Please remove the towel.", "Please remove the Prajiad.", "Fix the chest protector."], c: 0, ex: "✓ 'Please remove your jacket.'" },
  { en: "The Wai Kru is finished and it is time for the bout to start. Tell the corner they can equip the kask.", tr: "Wai Kru bitti ve maçın başlama zamanı geldi. Köşeye kaskı takabileceklerini söylüyorsun.", q: "Ne söylersin?", opts: ["You may put on the headguard/Headguard on.", "You may remove the headguard/Headguard off.", "Put on your Mongkon/Mongkon on.", "Fix the headguard."], c: 0, ex: "✓ 'You may put on the headguard/Headguard on.'" },
  { en: "The match is completely over. Tell the seconds they can take off the athlete's kask.", tr: "Maç tamamen bitti. Köşe görevlilerine sporcunun kaskını çıkarabileceklerini söylüyorsun.", q: "Ne söylersin?", opts: ["You may remove the headguard/Headguard off.", "Remove your Mongkon.", "Do not remove the gloves.", "You may put on the headguard/Headguard on."], c: 0, ex: "✓ 'You may remove the headguard/Headguard off.'" },
  { en: "The bout is over, but the official decision hasn't been announced yet. A second tries to untie the gloves. Stop them.", tr: "Maç bitti ancak resmi karar henüz anons edilmedi. Bir yardımcı eldivenleri çözmeye çalışıyor. Onu durduruyorsun.", q: "Ne söylersin?", opts: ["Do not remove the gloves.", "Fix the gloves.", "Tape the gloves.", "Can I see your gloves?"], c: 0, ex: "✓ 'Do not remove the gloves.'" },
  { en: "The round is starting and the seconds forgot their water bottle on the canvas. Tell them to take it.", tr: "Raund başlıyor ve köşe görevlisi su şişesini ring zemininde unuttu. Almalarını söylüyorsun.", q: "Ne söylersin?", opts: ["Please take the water bottle.", "Do not use too much water.", "Please remove the towel.", "Fix the chest protector."], c: 0, ex: "✓ 'Please take the water bottle.'" },
  { en: "The second is pouring too much water on the athlete during the break, making the canvas wet. Warn them.", tr: "Mola sırasında köşe görevlisi, sporcunun üstüne çok fazla su döküyor ve ring zeminini ıslatıyor. Onları uyarıyorsun.", q: "Ne söylersin?", opts: ["Do not use too much water.", "Please take the water bottle.", "Fix the elbow guard.", "Too much Vaseline. Please wipe it off."], c: 0, ex: "✓ 'Do not use too much water.'" },
  { en: "During a break, you notice the athlete's elbow guard is slipping. Tell the coach to correct it.", tr: "Mola esnasında sporcunun dirsekliğinin kaydığını fark ediyorsun. Antrenöre düzeltmesini söylüyorsun.", q: "Ne söylersin?", opts: ["Fix the elbow guard.", "Tape the shin guards.", "Fix the chest protector.", "Please remove the Prajiad."], c: 0, ex: "✓ 'Fix the elbow guard.'" },
  { en: "The athlete's shin guards keep shifting during the action. Tell the corner to secure them with tape.", tr: "Maç esnasında sporcunun kaval koruyucuları sürekli dönüyor. Köşeye onları bantla sabitlemelerini söylüyorsun.", q: "Ne söylersin?", opts: ["Tape the shin guards.", "Tape the gloves.", "Fix the headguard.", "Fix the chest protector."], c: 0, ex: "✓ 'Tape the shin guards.'" },
  { en: "The corner left a towel hanging on the ropes just before the round starts. Tell them to remove it.", tr: "Raund başlamadan hemen önce köşe iplerde bir havlu asılı bıraktı. Havluyu kaldırmalarını söylüyorsun.", q: "Ne söylersin?", opts: ["Please remove the towel.", "Please remove the Prajiad.", "Please lean over the ropes.", "Tape the gloves."], c: 0, ex: "✓ 'Please remove the towel.'" },
  { en: "During the break, one of the second is leaning inside of the ring under the ropes. Tell him/her to lean over the ropes.", tr: "Ara esnasında yardımcılar iplerin arasından ringin içine uzanıyor. İplerin üstünden uzanmasını söylüyorsun.", q: "Ne söylersin?", opts: ["Please lean over the ropes.", "Please remove the towel.", "Step back.", "Tape the gloves."], c: 0, ex: "✓ 'Please lean over the ropes.'" }
];

// ── JUDGE SEKME SENARYO PRATİĞİ ──
window.QUIZ_JUDGE = [
  { sit: "**EN: A media staff or photographer gets too close to your judging table or blocks your view. Tell them to move behind.**\nTR: Medya görevlisi fark etmeden Yan Hakem masasına çok yaklaştı veya önüne geçti. Geri gitmesini söylüyorsun.", opts: ["A. Please step back/move.", "B. No scorecards left.", "C. The scorecard is finished.", "D. I need a pen, please."], c: 0 },
  { sit: "**EN: You used your last paper scorecard. Inform the jury about the situation.**\nTR: Masada skor kartı kalmadı. Jüriyi bilgilendiriyorsun.", opts: ["A. I need a pen, please.", "B. The scorecard is finished.", "C. No scorecards left.", "D. Everything is okay."], c: 2 },
  { sit: "**EN: You cannot find your pen. Request one from the jury.**\nTR: Kalemini bulamıyorsun. Jüriden rica ediyorsun.", opts: ["A. I need a pen, please.", "B. Everything is okay.", "C. The scorecard is finished.", "D. I am pressing the button."], c: 0 },
  { sit: "**EN: There is a technical glitch on the scoreboard and the Jury asks if your device is responding. Inform them that you are active.**\nTR: Skor ekranında teknik bir sorun var ve jüri cihazınızın yanıt verip vermediğini soruyor. Jüriye butona bastığını bildiriyorsun.", opts: ["A. I am pressing the button.", "B. I did not press the button.", "C. I need a pen, please.", "D. I pressed the wrong button."], c: 0 },
  { sit: "**EN: During the system check, you want to state that you haven't touched your scoring button.**\nTR: Cihaz kontrolü gerçekleştirilirken butona basmadığını bildiriyorsun.", opts: ["A. I am pressing the button.", "B. I did not press the button.", "C. I pressed the wrong button.", "D. I reset the score by mistake."], c: 1 },
  { sit: "**EN: During the system check, you accidentally hit the wrong button. Inform the Jury.**\nTR: Cihaz kontrolü gerçekleştirirken yanlış butona bastın ve bunu Jüriye bildir.", opts: ["A. I pressed the wrong button.", "B. I gave the point to the wrong corner.", "C. I reset the score by mistake.", "D. The cable came out."], c: 0 },
  { sit: "**EN: Your finger slips during the active round and you hit the reset option by accident. Inform the jury.**\nTR: Maç esnasında yanlışlıkla resetleme tuşuna bastın. Jüriyi bilgilendiriyorsun.", opts: ["A. I pressed the wrong button.", "B. I reset the score by mistake.", "C. I did not press the button.", "D. Everything is okay."], c: 1 },
  { sit: "**EN: Your electronic scoring pad not working because the connection wire is pulled. Inform the Jüri immediately.**\nTR: Maç esnasında cihazın fişi/kablosu çıktığı için çalışmıyor. Jüriye derhal bilgi veriyorsun.", opts: ["A. The cable came out/Cable unplugged.", "B. Everything is okay.", "C. I did not press the button.", "D. I reset the score by mistake."], c: 0 },
  { sit: "**EN: You meant to give the round to the red corner but accidentally clicked the blue corner's button. Report the error.**\nTR: Maç esnasında yanlış köşeye puan bastın. Bunu bildiriyorsun.", opts: ["A. The cable came out/Cable unplugged.", "B. Everything is okay.", "C. I did not press the button.", "D. I gave the point to the wrong corner."], c: 3 },
  { sit: "**EN: The Jury asks if your electronic pad is working correctly now after the system check. Confirm that there are no issues.**\nTR: Sistem kontrolünden sonra Jüri cihazının çalışıp çalışmadığını soruyor. Her şeyin yolunda olduğunu bildiriyorsun.", opts: ["A. Everything is okay.", "B. I did not press the button.", "C. I am pressing the button.", "D. The scorecard is finished."], c: 0 }
];

// ── TIMEKEEPER SEKME SENARYO PRATİĞİ ──
window.QUIZ_TIMEKEEPER = [
  { sit: "**EN: The Rsportz system freezes during the round. Inform the Jury immediately.**\nTR: Maç esnasında Rsportz sistemi dondu. Jüriye derhal bilgi veriyorsun.", opts: ["A. I stopped the time.", "B. The system has stopped/System stopped.", "C. No sound.", "D. I started the time."], c: 1 },
  { sit: "**EN: You started playing the Wai Kru music on the computer but no audio comes out of the speakers. Report the issue.**\nTR: Wai Kru müziğini bilgisayardan başlattın ama hoparlörlerinden ses gelmiyor. Durumu bildiriyorsun.", opts: ["A. The system has stopped.", "B. I stopped the time.", "C. There is no sound/No sound.", "D. The winner is the blue corner."], c: 2 },
  { sit: "**EN: The referee commands TIME for an equipment fix. Confirm that you paused the official clock.**\nTR: Orta hakem bir ekipman düzeltmesi için TIME komutu verdi. Resmi süreyi durdurduğunu onaylıyorsun.", opts: ["A. I started the time.", "B. The system has stopped.", "C. I stopped the time.", "D. There is no sound/No sound."], c: 2 },
  { sit: "**EN: The referee commands \"CHOK\" (Fight) to resume the action. Confirm that you restarted the clock.**\nTR: Orta hakem maçı yeniden başlatmak için \"ÇOK\" (Dövüş) komutu verdi. Süreyi tekrar başlattığını onaylıyorsun.", opts: ["A. I started the time.", "B. The system has stopped.", "C. I stopped the time.", "D. There is no sound/No sound."], c: 0 }
];

// ── ANNOUNCER SEKME SENARYO PRATİĞİ ──
window.QUIZ_ANNOUNCER = [
  { sit: "**EN: Prepare the upcoming fighters by announcing that they should get ready.**\nTR: Sıradaki maçın sporcularına hazır olmaları gerektiğini anons ediyorsun.", opts: ["A. Next bout, red corner [Name] from [Country], blue corner [Name] from [Country], please get ready.", "B. Ring A, Bout number 2, red corner [Name] from [Country] to the ring area!", "C. This is the final call!", "D. Seconds out!"], c: 0 },
  { sit: "**EN: Call the red corner athlete of the second bout in Ring A to enter the ring area immediately.**\nTR: A ringindeki 2. maçın kırmızı köşe sporcusunu derhal ring alanına çağırıyorsun.", opts: ["A. Ring B, Bout number 3, blue corner [Name] from [Country] to the ring area!", "B. Next bout, red corner [Name] from [Country], blue corner [Name] from [Country], please get ready.", "C. Ring A, Bout number 2, red corner [Name] from [Country] to the ring area!", "D. The winner is the red corner."], c: 2 },
  { sit: "**EN: An athlete has not shown up after the announcements. Make the definitive warning before Walk-Over.**\nTR: Bir sporcu yapılan anonslara rağmen gelmedi. Walk-Over öncesindeki son çağrıyı yapıyorsun.", opts: ["A. The bouts are paused for one hour.", "B. Next bout, get ready.", "C. The winner is the blue corner.", "D. Final call!"], c: 3 },
  { sit: "**EN: The official decision is handed to you. Announce the victory of the blue corner.**\nTR: Resmi karar sana ulaştı. Mavi köşenin kazandığını anons ediyorsun.", opts: ["A. The winner is the red corner.", "B. The winner is the blue corner.", "C. Final call!", "D. Next bout, get ready."], c: 1 },
  { sit: "**EN: The Technical Delegate decides to take a official lunch break. Announce the schedule pause.**\nTR: Teknik Delege resmi bir öğle arası verme kararı aldı. Seansa ara verildiğini anons ediyorsun.", opts: ["A. The bouts are paused for one hour.", "B. Please lean over the ropes.", "C. Next bout, get ready.", "D. This is the final call!"], c: 0 },
  { sit: "**EN: The one-minute break is ending, and the next round is about to start. Order the seconds to leave the canvas.**\nTR: Bir dakikalık mola bitiyor ve yeni raund başlamak üzere. Köşe görevlilerinin ringden dışarı çıkmasını söylüyorsun.", opts: ["A. Please lean over the ropes.", "B. Seconds out!", "C. Please remove the towel.", "D. Step back."], c: 1 }
];